@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.almostreliable.morejs.features.structure;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;