@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.almostreliable.summoningrituals.inventory;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;