@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.almostreliable.lootjs.forge.gametest;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;