@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.xkmc.modulargolems.init.registrate;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;