@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.xkmc.l2artifacts.network;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;