@ParametersAreNonnullByDefault
@FieldsAndMethodsAreNonnullByDefault
package mezz.jei.core.util;

import javax.annotation.ParametersAreNonnullByDefault;
import mezz.jei.core.FieldsAndMethodsAreNonnullByDefault;