@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package extensions.net.minecraft.world.item.ItemStack;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;