@ParametersAreNonnullByDefault
@FieldsAndMethodsAreNonnullByDefault
package mezz.jei.core.search;

import javax.annotation.ParametersAreNonnullByDefault;
import mezz.jei.core.FieldsAndMethodsAreNonnullByDefault;