@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.xkmc.modulargolems.compat.materials.l2hostility;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;