@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraftforge.resource;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;