@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.xkmc.modulargolems.content.recipe;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;