@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.almostreliable.morejs.mixin.villager;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;