@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.almostreliable.lootjs.util;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;