@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package extensions.net.minecraft.world.entity.LivingEntity;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;