@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.almostreliable.summoningrituals.recipe;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;