@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.almostreliable.summoningrituals.altar;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;