@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.xkmc.l2artifacts.content.config;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;