@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.almostreliable.lootjs.core;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;