@ParametersAreNonnullByDefault
@FieldsAndMethodsAreNonnullByDefault
package mezz.jei.forge.plugins;

import javax.annotation.ParametersAreNonnullByDefault;
import mezz.jei.core.FieldsAndMethodsAreNonnullByDefault;