@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.xkmc.l2artifacts.init.registrate.entries;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;