@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.almostreliable.morejs.core;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;