@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package mezz.jei.gui.ingredients;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;