package com.github.alexthe666.citadel.repack.jcodec.containers.mp4;

import com.github.alexthe666.citadel.repack.jcodec.containers.mp4.boxes.AudioSampleEntry;
import com.github.alexthe666.citadel.repack.jcodec.containers.mp4.boxes.SampleEntry;
import com.github.alexthe666.citadel.repack.jcodec.containers.mp4.boxes.TimecodeSampleEntry;
import com.github.alexthe666.citadel.repack.jcodec.containers.mp4.boxes.VideoSampleEntry;
import com.github.alexthe666.citadel.repack.jcodec.platform.Platform;

public class SampleBoxes extends Boxes {

    public SampleBoxes() {
        this.clear();
        this.override("ap4h", VideoSampleEntry.class);
        this.override("apch", VideoSampleEntry.class);
        this.override("apcn", VideoSampleEntry.class);
        this.override("apcs", VideoSampleEntry.class);
        this.override("apco", VideoSampleEntry.class);
        this.override("avc1", VideoSampleEntry.class);
        this.override("cvid", VideoSampleEntry.class);
        this.override("jpeg", VideoSampleEntry.class);
        this.override("smc ", VideoSampleEntry.class);
        this.override("rle ", VideoSampleEntry.class);
        this.override("rpza", VideoSampleEntry.class);
        this.override("kpcd", VideoSampleEntry.class);
        this.override("png ", VideoSampleEntry.class);
        this.override("mjpa", VideoSampleEntry.class);
        this.override("mjpb", VideoSampleEntry.class);
        this.override("SVQ1", VideoSampleEntry.class);
        this.override("SVQ3", VideoSampleEntry.class);
        this.override("mp4v", VideoSampleEntry.class);
        this.override("dvc ", VideoSampleEntry.class);
        this.override("dvcp", VideoSampleEntry.class);
        this.override("gif ", VideoSampleEntry.class);
        this.override("h263", VideoSampleEntry.class);
        this.override("tiff", VideoSampleEntry.class);
        this.override("raw ", VideoSampleEntry.class);
        this.override("2vuY", VideoSampleEntry.class);
        this.override("yuv2", VideoSampleEntry.class);
        this.override("v308", VideoSampleEntry.class);
        this.override("v408", VideoSampleEntry.class);
        this.override("v216", VideoSampleEntry.class);
        this.override("v410", VideoSampleEntry.class);
        this.override("v210", VideoSampleEntry.class);
        this.override("m2v1", VideoSampleEntry.class);
        this.override("m1v1", VideoSampleEntry.class);
        this.override("xd5b", VideoSampleEntry.class);
        this.override("dv5n", VideoSampleEntry.class);
        this.override("jp2h", VideoSampleEntry.class);
        this.override("mjp2", VideoSampleEntry.class);
        this.override("ac-3", AudioSampleEntry.class);
        this.override("cac3", AudioSampleEntry.class);
        this.override("ima4", AudioSampleEntry.class);
        this.override("aac ", AudioSampleEntry.class);
        this.override("celp", AudioSampleEntry.class);
        this.override("hvxc", AudioSampleEntry.class);
        this.override("twvq", AudioSampleEntry.class);
        this.override(".mp1", AudioSampleEntry.class);
        this.override(".mp2", AudioSampleEntry.class);
        this.override("midi", AudioSampleEntry.class);
        this.override("apvs", AudioSampleEntry.class);
        this.override("alac", AudioSampleEntry.class);
        this.override("aach", AudioSampleEntry.class);
        this.override("aacl", AudioSampleEntry.class);
        this.override("aace", AudioSampleEntry.class);
        this.override("aacf", AudioSampleEntry.class);
        this.override("aacp", AudioSampleEntry.class);
        this.override("aacs", AudioSampleEntry.class);
        this.override("samr", AudioSampleEntry.class);
        this.override("AUDB", AudioSampleEntry.class);
        this.override("ilbc", AudioSampleEntry.class);
        this.override(Platform.stringFromBytes(new byte[] { 109, 115, 0, 17 }), AudioSampleEntry.class);
        this.override(Platform.stringFromBytes(new byte[] { 109, 115, 0, 49 }), AudioSampleEntry.class);
        this.override("aes3", AudioSampleEntry.class);
        this.override("NONE", AudioSampleEntry.class);
        this.override("raw ", AudioSampleEntry.class);
        this.override("twos", AudioSampleEntry.class);
        this.override("sowt", AudioSampleEntry.class);
        this.override("MAC3 ", AudioSampleEntry.class);
        this.override("MAC6 ", AudioSampleEntry.class);
        this.override("ima4", AudioSampleEntry.class);
        this.override("fl32", AudioSampleEntry.class);
        this.override("fl64", AudioSampleEntry.class);
        this.override("in24", AudioSampleEntry.class);
        this.override("in32", AudioSampleEntry.class);
        this.override("ulaw", AudioSampleEntry.class);
        this.override("alaw", AudioSampleEntry.class);
        this.override("dvca", AudioSampleEntry.class);
        this.override("QDMC", AudioSampleEntry.class);
        this.override("QDM2", AudioSampleEntry.class);
        this.override("Qclp", AudioSampleEntry.class);
        this.override(".mp3", AudioSampleEntry.class);
        this.override("mp4a", AudioSampleEntry.class);
        this.override("lpcm", AudioSampleEntry.class);
        this.override("tmcd", TimecodeSampleEntry.class);
        this.override("time", TimecodeSampleEntry.class);
        this.override("c608", SampleEntry.class);
        this.override("c708", SampleEntry.class);
        this.override("text", SampleEntry.class);
        this.override("fdsc", SampleEntry.class);
    }
}