@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.almostreliable.morejs.features;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;