@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.edwinmindcraft.origins.api.registry;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;