package net.minecraft.client.model.geom;

import com.google.common.collect.ImmutableMap;
import com.google.common.collect.ImmutableMap.Builder;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import net.minecraft.client.model.AllayModel;
import net.minecraft.client.model.ArmorStandArmorModel;
import net.minecraft.client.model.ArmorStandModel;
import net.minecraft.client.model.AxolotlModel;
import net.minecraft.client.model.BatModel;
import net.minecraft.client.model.BeeModel;
import net.minecraft.client.model.BlazeModel;
import net.minecraft.client.model.BoatModel;
import net.minecraft.client.model.BookModel;
import net.minecraft.client.model.CamelModel;
import net.minecraft.client.model.ChestBoatModel;
import net.minecraft.client.model.ChestRaftModel;
import net.minecraft.client.model.ChestedHorseModel;
import net.minecraft.client.model.ChickenModel;
import net.minecraft.client.model.CodModel;
import net.minecraft.client.model.CowModel;
import net.minecraft.client.model.CreeperModel;
import net.minecraft.client.model.DolphinModel;
import net.minecraft.client.model.DrownedModel;
import net.minecraft.client.model.ElytraModel;
import net.minecraft.client.model.EndermanModel;
import net.minecraft.client.model.EndermiteModel;
import net.minecraft.client.model.EvokerFangsModel;
import net.minecraft.client.model.FoxModel;
import net.minecraft.client.model.FrogModel;
import net.minecraft.client.model.GhastModel;
import net.minecraft.client.model.GoatModel;
import net.minecraft.client.model.GuardianModel;
import net.minecraft.client.model.HoglinModel;
import net.minecraft.client.model.HorseModel;
import net.minecraft.client.model.HumanoidArmorModel;
import net.minecraft.client.model.HumanoidModel;
import net.minecraft.client.model.IllagerModel;
import net.minecraft.client.model.IronGolemModel;
import net.minecraft.client.model.LavaSlimeModel;
import net.minecraft.client.model.LeashKnotModel;
import net.minecraft.client.model.LlamaModel;
import net.minecraft.client.model.LlamaSpitModel;
import net.minecraft.client.model.MinecartModel;
import net.minecraft.client.model.OcelotModel;
import net.minecraft.client.model.PandaModel;
import net.minecraft.client.model.ParrotModel;
import net.minecraft.client.model.PhantomModel;
import net.minecraft.client.model.PigModel;
import net.minecraft.client.model.PiglinHeadModel;
import net.minecraft.client.model.PiglinModel;
import net.minecraft.client.model.PlayerModel;
import net.minecraft.client.model.PolarBearModel;
import net.minecraft.client.model.PufferfishBigModel;
import net.minecraft.client.model.PufferfishMidModel;
import net.minecraft.client.model.PufferfishSmallModel;
import net.minecraft.client.model.RabbitModel;
import net.minecraft.client.model.RaftModel;
import net.minecraft.client.model.RavagerModel;
import net.minecraft.client.model.SalmonModel;
import net.minecraft.client.model.SheepFurModel;
import net.minecraft.client.model.SheepModel;
import net.minecraft.client.model.ShieldModel;
import net.minecraft.client.model.ShulkerBulletModel;
import net.minecraft.client.model.ShulkerModel;
import net.minecraft.client.model.SilverfishModel;
import net.minecraft.client.model.SkeletonModel;
import net.minecraft.client.model.SkullModel;
import net.minecraft.client.model.SlimeModel;
import net.minecraft.client.model.SnifferModel;
import net.minecraft.client.model.SnowGolemModel;
import net.minecraft.client.model.SpiderModel;
import net.minecraft.client.model.SquidModel;
import net.minecraft.client.model.StriderModel;
import net.minecraft.client.model.TadpoleModel;
import net.minecraft.client.model.TridentModel;
import net.minecraft.client.model.TropicalFishModelA;
import net.minecraft.client.model.TropicalFishModelB;
import net.minecraft.client.model.TurtleModel;
import net.minecraft.client.model.VexModel;
import net.minecraft.client.model.VillagerModel;
import net.minecraft.client.model.WardenModel;
import net.minecraft.client.model.WitchModel;
import net.minecraft.client.model.WitherBossModel;
import net.minecraft.client.model.WolfModel;
import net.minecraft.client.model.ZombieVillagerModel;
import net.minecraft.client.model.dragon.DragonHeadModel;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.renderer.blockentity.BannerRenderer;
import net.minecraft.client.renderer.blockentity.BedRenderer;
import net.minecraft.client.renderer.blockentity.BellRenderer;
import net.minecraft.client.renderer.blockentity.ChestRenderer;
import net.minecraft.client.renderer.blockentity.ConduitRenderer;
import net.minecraft.client.renderer.blockentity.DecoratedPotRenderer;
import net.minecraft.client.renderer.blockentity.HangingSignRenderer;
import net.minecraft.client.renderer.blockentity.SignRenderer;
import net.minecraft.client.renderer.entity.EndCrystalRenderer;
import net.minecraft.client.renderer.entity.EnderDragonRenderer;
import net.minecraft.client.renderer.entity.WitherSkullRenderer;
import net.minecraft.client.renderer.entity.layers.SpinAttackEffectLayer;
import net.minecraft.world.entity.vehicle.Boat;
import net.minecraft.world.level.block.state.properties.WoodType;

public class LayerDefinitions {

    private static final CubeDeformation FISH_PATTERN_DEFORMATION = new CubeDeformation(0.008F);

    private static final CubeDeformation OUTER_ARMOR_DEFORMATION = new CubeDeformation(1.0F);

    private static final CubeDeformation INNER_ARMOR_DEFORMATION = new CubeDeformation(0.5F);

    public static Map<ModelLayerLocation, LayerDefinition> createRoots() {
        Builder<ModelLayerLocation, LayerDefinition> $$0 = ImmutableMap.builder();
        LayerDefinition $$1 = LayerDefinition.create(HumanoidModel.createMesh(CubeDeformation.NONE, 0.0F), 64, 64);
        LayerDefinition $$2 = LayerDefinition.create(HumanoidArmorModel.createBodyLayer(OUTER_ARMOR_DEFORMATION), 64, 32);
        LayerDefinition $$3 = LayerDefinition.create(HumanoidArmorModel.createBodyLayer(new CubeDeformation(1.02F)), 64, 32);
        LayerDefinition $$4 = LayerDefinition.create(HumanoidArmorModel.createBodyLayer(INNER_ARMOR_DEFORMATION), 64, 32);
        LayerDefinition $$5 = MinecartModel.createBodyLayer();
        LayerDefinition $$6 = SkullModel.createMobHeadLayer();
        LayerDefinition $$7 = LayerDefinition.create(HorseModel.createBodyMesh(CubeDeformation.NONE), 64, 64);
        LayerDefinition $$8 = IllagerModel.createBodyLayer();
        LayerDefinition $$9 = CowModel.createBodyLayer();
        LayerDefinition $$10 = LayerDefinition.create(OcelotModel.createBodyMesh(CubeDeformation.NONE), 64, 32);
        LayerDefinition $$11 = LayerDefinition.create(PiglinModel.createMesh(CubeDeformation.NONE), 64, 64);
        LayerDefinition $$12 = LayerDefinition.create(PiglinHeadModel.createHeadModel(), 64, 64);
        LayerDefinition $$13 = SkullModel.createHumanoidHeadLayer();
        LayerDefinition $$14 = LlamaModel.createBodyLayer(CubeDeformation.NONE);
        LayerDefinition $$15 = StriderModel.createBodyLayer();
        LayerDefinition $$16 = HoglinModel.createBodyLayer();
        LayerDefinition $$17 = SkeletonModel.createBodyLayer();
        LayerDefinition $$18 = LayerDefinition.create(VillagerModel.createBodyModel(), 64, 64);
        LayerDefinition $$19 = SpiderModel.createSpiderBodyLayer();
        $$0.put(ModelLayers.ALLAY, AllayModel.createBodyLayer());
        $$0.put(ModelLayers.ARMOR_STAND, ArmorStandModel.createBodyLayer());
        $$0.put(ModelLayers.ARMOR_STAND_INNER_ARMOR, ArmorStandArmorModel.createBodyLayer(INNER_ARMOR_DEFORMATION));
        $$0.put(ModelLayers.ARMOR_STAND_OUTER_ARMOR, ArmorStandArmorModel.createBodyLayer(OUTER_ARMOR_DEFORMATION));
        $$0.put(ModelLayers.AXOLOTL, AxolotlModel.createBodyLayer());
        $$0.put(ModelLayers.BANNER, BannerRenderer.createBodyLayer());
        $$0.put(ModelLayers.BAT, BatModel.createBodyLayer());
        $$0.put(ModelLayers.BED_FOOT, BedRenderer.createFootLayer());
        $$0.put(ModelLayers.BED_HEAD, BedRenderer.createHeadLayer());
        $$0.put(ModelLayers.BEE, BeeModel.createBodyLayer());
        $$0.put(ModelLayers.BELL, BellRenderer.createBodyLayer());
        $$0.put(ModelLayers.BLAZE, BlazeModel.createBodyLayer());
        $$0.put(ModelLayers.BOOK, BookModel.createBodyLayer());
        $$0.put(ModelLayers.CAT, $$10);
        $$0.put(ModelLayers.CAT_COLLAR, LayerDefinition.create(OcelotModel.createBodyMesh(new CubeDeformation(0.01F)), 64, 32));
        $$0.put(ModelLayers.CAMEL, CamelModel.createBodyLayer());
        $$0.put(ModelLayers.CAVE_SPIDER, $$19);
        $$0.put(ModelLayers.CHEST, ChestRenderer.createSingleBodyLayer());
        $$0.put(ModelLayers.CHEST_MINECART, $$5);
        $$0.put(ModelLayers.CHICKEN, ChickenModel.createBodyLayer());
        $$0.put(ModelLayers.COD, CodModel.createBodyLayer());
        $$0.put(ModelLayers.COMMAND_BLOCK_MINECART, $$5);
        $$0.put(ModelLayers.CONDUIT_EYE, ConduitRenderer.createEyeLayer());
        $$0.put(ModelLayers.CONDUIT_WIND, ConduitRenderer.createWindLayer());
        $$0.put(ModelLayers.CONDUIT_SHELL, ConduitRenderer.createShellLayer());
        $$0.put(ModelLayers.CONDUIT_CAGE, ConduitRenderer.createCageLayer());
        $$0.put(ModelLayers.COW, $$9);
        $$0.put(ModelLayers.CREEPER, CreeperModel.createBodyLayer(CubeDeformation.NONE));
        $$0.put(ModelLayers.CREEPER_ARMOR, CreeperModel.createBodyLayer(new CubeDeformation(2.0F)));
        $$0.put(ModelLayers.CREEPER_HEAD, $$6);
        $$0.put(ModelLayers.DECORATED_POT_BASE, DecoratedPotRenderer.createBaseLayer());
        $$0.put(ModelLayers.DECORATED_POT_SIDES, DecoratedPotRenderer.createSidesLayer());
        $$0.put(ModelLayers.DOLPHIN, DolphinModel.createBodyLayer());
        $$0.put(ModelLayers.DONKEY, ChestedHorseModel.createBodyLayer());
        $$0.put(ModelLayers.DOUBLE_CHEST_LEFT, ChestRenderer.createDoubleBodyLeftLayer());
        $$0.put(ModelLayers.DOUBLE_CHEST_RIGHT, ChestRenderer.createDoubleBodyRightLayer());
        $$0.put(ModelLayers.DRAGON_SKULL, DragonHeadModel.createHeadLayer());
        $$0.put(ModelLayers.DROWNED, DrownedModel.createBodyLayer(CubeDeformation.NONE));
        $$0.put(ModelLayers.DROWNED_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.DROWNED_OUTER_ARMOR, $$4);
        $$0.put(ModelLayers.DROWNED_OUTER_LAYER, DrownedModel.createBodyLayer(new CubeDeformation(0.25F)));
        $$0.put(ModelLayers.ELDER_GUARDIAN, GuardianModel.createBodyLayer());
        $$0.put(ModelLayers.ELYTRA, ElytraModel.createLayer());
        $$0.put(ModelLayers.ENDERMAN, EndermanModel.createBodyLayer());
        $$0.put(ModelLayers.ENDERMITE, EndermiteModel.createBodyLayer());
        $$0.put(ModelLayers.ENDER_DRAGON, EnderDragonRenderer.createBodyLayer());
        $$0.put(ModelLayers.END_CRYSTAL, EndCrystalRenderer.createBodyLayer());
        $$0.put(ModelLayers.EVOKER, $$8);
        $$0.put(ModelLayers.EVOKER_FANGS, EvokerFangsModel.createBodyLayer());
        $$0.put(ModelLayers.FOX, FoxModel.createBodyLayer());
        $$0.put(ModelLayers.FROG, FrogModel.createBodyLayer());
        $$0.put(ModelLayers.FURNACE_MINECART, $$5);
        $$0.put(ModelLayers.GHAST, GhastModel.createBodyLayer());
        $$0.put(ModelLayers.GIANT, $$1);
        $$0.put(ModelLayers.GIANT_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.GIANT_OUTER_ARMOR, $$2);
        $$0.put(ModelLayers.GLOW_SQUID, SquidModel.createBodyLayer());
        $$0.put(ModelLayers.GOAT, GoatModel.createBodyLayer());
        $$0.put(ModelLayers.GUARDIAN, GuardianModel.createBodyLayer());
        $$0.put(ModelLayers.HOGLIN, $$16);
        $$0.put(ModelLayers.HOPPER_MINECART, $$5);
        $$0.put(ModelLayers.HORSE, $$7);
        $$0.put(ModelLayers.HORSE_ARMOR, LayerDefinition.create(HorseModel.createBodyMesh(new CubeDeformation(0.1F)), 64, 64));
        $$0.put(ModelLayers.HUSK, $$1);
        $$0.put(ModelLayers.HUSK_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.HUSK_OUTER_ARMOR, $$2);
        $$0.put(ModelLayers.ILLUSIONER, $$8);
        $$0.put(ModelLayers.IRON_GOLEM, IronGolemModel.createBodyLayer());
        $$0.put(ModelLayers.LEASH_KNOT, LeashKnotModel.createBodyLayer());
        $$0.put(ModelLayers.LLAMA, $$14);
        $$0.put(ModelLayers.LLAMA_DECOR, LlamaModel.createBodyLayer(new CubeDeformation(0.5F)));
        $$0.put(ModelLayers.LLAMA_SPIT, LlamaSpitModel.createBodyLayer());
        $$0.put(ModelLayers.MAGMA_CUBE, LavaSlimeModel.createBodyLayer());
        $$0.put(ModelLayers.MINECART, $$5);
        $$0.put(ModelLayers.MOOSHROOM, $$9);
        $$0.put(ModelLayers.MULE, ChestedHorseModel.createBodyLayer());
        $$0.put(ModelLayers.OCELOT, $$10);
        $$0.put(ModelLayers.PANDA, PandaModel.createBodyLayer());
        $$0.put(ModelLayers.PARROT, ParrotModel.createBodyLayer());
        $$0.put(ModelLayers.PHANTOM, PhantomModel.createBodyLayer());
        $$0.put(ModelLayers.PIG, PigModel.createBodyLayer(CubeDeformation.NONE));
        $$0.put(ModelLayers.PIG_SADDLE, PigModel.createBodyLayer(new CubeDeformation(0.5F)));
        $$0.put(ModelLayers.PIGLIN, $$11);
        $$0.put(ModelLayers.PIGLIN_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.PIGLIN_OUTER_ARMOR, $$3);
        $$0.put(ModelLayers.PIGLIN_BRUTE, $$11);
        $$0.put(ModelLayers.PIGLIN_BRUTE_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.PIGLIN_BRUTE_OUTER_ARMOR, $$3);
        $$0.put(ModelLayers.PIGLIN_HEAD, $$12);
        $$0.put(ModelLayers.PILLAGER, $$8);
        $$0.put(ModelLayers.PLAYER, LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, false), 64, 64));
        $$0.put(ModelLayers.PLAYER_HEAD, $$13);
        $$0.put(ModelLayers.PLAYER_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.PLAYER_OUTER_ARMOR, $$2);
        $$0.put(ModelLayers.PLAYER_SLIM, LayerDefinition.create(PlayerModel.createMesh(CubeDeformation.NONE, true), 64, 64));
        $$0.put(ModelLayers.PLAYER_SLIM_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.PLAYER_SLIM_OUTER_ARMOR, $$2);
        $$0.put(ModelLayers.PLAYER_SPIN_ATTACK, SpinAttackEffectLayer.createLayer());
        $$0.put(ModelLayers.POLAR_BEAR, PolarBearModel.createBodyLayer());
        $$0.put(ModelLayers.PUFFERFISH_BIG, PufferfishBigModel.createBodyLayer());
        $$0.put(ModelLayers.PUFFERFISH_MEDIUM, PufferfishMidModel.createBodyLayer());
        $$0.put(ModelLayers.PUFFERFISH_SMALL, PufferfishSmallModel.createBodyLayer());
        $$0.put(ModelLayers.RABBIT, RabbitModel.createBodyLayer());
        $$0.put(ModelLayers.RAVAGER, RavagerModel.createBodyLayer());
        $$0.put(ModelLayers.SALMON, SalmonModel.createBodyLayer());
        $$0.put(ModelLayers.SHEEP, SheepModel.createBodyLayer());
        $$0.put(ModelLayers.SHEEP_FUR, SheepFurModel.createFurLayer());
        $$0.put(ModelLayers.SHIELD, ShieldModel.createLayer());
        $$0.put(ModelLayers.SHULKER, ShulkerModel.createBodyLayer());
        $$0.put(ModelLayers.SHULKER_BULLET, ShulkerBulletModel.createBodyLayer());
        $$0.put(ModelLayers.SILVERFISH, SilverfishModel.createBodyLayer());
        $$0.put(ModelLayers.SKELETON, $$17);
        $$0.put(ModelLayers.SKELETON_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.SKELETON_OUTER_ARMOR, $$2);
        $$0.put(ModelLayers.SKELETON_HORSE, $$7);
        $$0.put(ModelLayers.SKELETON_SKULL, $$6);
        $$0.put(ModelLayers.SLIME, SlimeModel.createInnerBodyLayer());
        $$0.put(ModelLayers.SLIME_OUTER, SlimeModel.createOuterBodyLayer());
        $$0.put(ModelLayers.SNIFFER, SnifferModel.createBodyLayer());
        $$0.put(ModelLayers.SNOW_GOLEM, SnowGolemModel.createBodyLayer());
        $$0.put(ModelLayers.SPAWNER_MINECART, $$5);
        $$0.put(ModelLayers.SPIDER, $$19);
        $$0.put(ModelLayers.SQUID, SquidModel.createBodyLayer());
        $$0.put(ModelLayers.STRAY, $$17);
        $$0.put(ModelLayers.STRAY_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.STRAY_OUTER_ARMOR, $$2);
        $$0.put(ModelLayers.STRAY_OUTER_LAYER, LayerDefinition.create(HumanoidModel.createMesh(new CubeDeformation(0.25F), 0.0F), 64, 32));
        $$0.put(ModelLayers.STRIDER, $$15);
        $$0.put(ModelLayers.STRIDER_SADDLE, $$15);
        $$0.put(ModelLayers.TADPOLE, TadpoleModel.createBodyLayer());
        $$0.put(ModelLayers.TNT_MINECART, $$5);
        $$0.put(ModelLayers.TRADER_LLAMA, $$14);
        $$0.put(ModelLayers.TRIDENT, TridentModel.createLayer());
        $$0.put(ModelLayers.TROPICAL_FISH_LARGE, TropicalFishModelB.createBodyLayer(CubeDeformation.NONE));
        $$0.put(ModelLayers.TROPICAL_FISH_LARGE_PATTERN, TropicalFishModelB.createBodyLayer(FISH_PATTERN_DEFORMATION));
        $$0.put(ModelLayers.TROPICAL_FISH_SMALL, TropicalFishModelA.createBodyLayer(CubeDeformation.NONE));
        $$0.put(ModelLayers.TROPICAL_FISH_SMALL_PATTERN, TropicalFishModelA.createBodyLayer(FISH_PATTERN_DEFORMATION));
        $$0.put(ModelLayers.TURTLE, TurtleModel.createBodyLayer());
        $$0.put(ModelLayers.VEX, VexModel.createBodyLayer());
        $$0.put(ModelLayers.VILLAGER, $$18);
        $$0.put(ModelLayers.VINDICATOR, $$8);
        $$0.put(ModelLayers.WARDEN, WardenModel.createBodyLayer());
        $$0.put(ModelLayers.WANDERING_TRADER, $$18);
        $$0.put(ModelLayers.WITCH, WitchModel.createBodyLayer());
        $$0.put(ModelLayers.WITHER, WitherBossModel.createBodyLayer(CubeDeformation.NONE));
        $$0.put(ModelLayers.WITHER_ARMOR, WitherBossModel.createBodyLayer(INNER_ARMOR_DEFORMATION));
        $$0.put(ModelLayers.WITHER_SKULL, WitherSkullRenderer.createSkullLayer());
        $$0.put(ModelLayers.WITHER_SKELETON, $$17);
        $$0.put(ModelLayers.WITHER_SKELETON_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.WITHER_SKELETON_OUTER_ARMOR, $$2);
        $$0.put(ModelLayers.WITHER_SKELETON_SKULL, $$6);
        $$0.put(ModelLayers.WOLF, WolfModel.createBodyLayer());
        $$0.put(ModelLayers.ZOGLIN, $$16);
        $$0.put(ModelLayers.ZOMBIE, $$1);
        $$0.put(ModelLayers.ZOMBIE_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.ZOMBIE_OUTER_ARMOR, $$2);
        $$0.put(ModelLayers.ZOMBIE_HEAD, $$13);
        $$0.put(ModelLayers.ZOMBIE_HORSE, $$7);
        $$0.put(ModelLayers.ZOMBIE_VILLAGER, ZombieVillagerModel.createBodyLayer());
        $$0.put(ModelLayers.ZOMBIE_VILLAGER_INNER_ARMOR, ZombieVillagerModel.createArmorLayer(INNER_ARMOR_DEFORMATION));
        $$0.put(ModelLayers.ZOMBIE_VILLAGER_OUTER_ARMOR, ZombieVillagerModel.createArmorLayer(OUTER_ARMOR_DEFORMATION));
        $$0.put(ModelLayers.ZOMBIFIED_PIGLIN, $$11);
        $$0.put(ModelLayers.ZOMBIFIED_PIGLIN_INNER_ARMOR, $$4);
        $$0.put(ModelLayers.ZOMBIFIED_PIGLIN_OUTER_ARMOR, $$3);
        LayerDefinition $$20 = BoatModel.createBodyModel();
        LayerDefinition $$21 = ChestBoatModel.createBodyModel();
        LayerDefinition $$22 = RaftModel.createBodyModel();
        LayerDefinition $$23 = ChestRaftModel.createBodyModel();
        for (Boat.Type $$24 : Boat.Type.values()) {
            if ($$24 == Boat.Type.BAMBOO) {
                $$0.put(ModelLayers.createBoatModelName($$24), $$22);
                $$0.put(ModelLayers.createChestBoatModelName($$24), $$23);
            } else {
                $$0.put(ModelLayers.createBoatModelName($$24), $$20);
                $$0.put(ModelLayers.createChestBoatModelName($$24), $$21);
            }
        }
        LayerDefinition $$25 = SignRenderer.createSignLayer();
        WoodType.values().forEach(p_171114_ -> $$0.put(ModelLayers.createSignModelName(p_171114_), $$25));
        LayerDefinition $$26 = HangingSignRenderer.createHangingSignLayer();
        WoodType.values().forEach(p_247864_ -> $$0.put(ModelLayers.createHangingSignModelName(p_247864_), $$26));
        ImmutableMap<ModelLayerLocation, LayerDefinition> $$27 = $$0.build();
        List<ModelLayerLocation> $$28 = (List<ModelLayerLocation>) ModelLayers.getKnownLocations().filter(p_171117_ -> !$$27.containsKey(p_171117_)).collect(Collectors.toList());
        if (!$$28.isEmpty()) {
            throw new IllegalStateException("Missing layer definitions: " + $$28);
        } else {
            return $$27;
        }
    }
}