@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.almostreliable.summoningrituals.util;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;