@ParametersAreNonnullByDefault
@FieldsAndMethodsAreNonnullByDefault
package mezz.jei.core.collect;

import javax.annotation.ParametersAreNonnullByDefault;
import mezz.jei.core.FieldsAndMethodsAreNonnullByDefault;