@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package mezz.jei.common.platform;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;