@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.almostreliable.lootjs.loot.condition;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;