@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package mezz.jei.gui.bookmarks;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;