@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.xkmc.l2artifacts.content.effects.persistent;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;