@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package vectorwing.farmersdelight.client.particle;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;