@ParametersAreNonnullByDefault
@FieldsAndMethodsAreNonnullByDefault
package mezz.jei.forge.plugins.forge;

import javax.annotation.ParametersAreNonnullByDefault;
import mezz.jei.core.FieldsAndMethodsAreNonnullByDefault;