@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.almostreliable.morejs.features.villager.trades;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;