@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.xkmc.modulargolems.content.menu.path;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;