package net.minecraft.util.datafix;

import com.google.common.collect.ImmutableMap;
import com.google.common.util.concurrent.ThreadFactoryBuilder;
import com.mojang.datafixers.DSL;
import com.mojang.datafixers.DataFixer;
import com.mojang.datafixers.DataFixerBuilder;
import com.mojang.datafixers.Typed;
import com.mojang.datafixers.DSL.TypeReference;
import com.mojang.datafixers.schemas.Schema;
import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.function.BiFunction;
import java.util.function.Function;
import java.util.function.UnaryOperator;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import net.minecraft.SharedConstants;
import net.minecraft.Util;
import net.minecraft.util.datafix.fixes.AbstractArrowPickupFix;
import net.minecraft.util.datafix.fixes.AddFlagIfNotPresentFix;
import net.minecraft.util.datafix.fixes.AddNewChoices;
import net.minecraft.util.datafix.fixes.AdvancementsFix;
import net.minecraft.util.datafix.fixes.AdvancementsRenameFix;
import net.minecraft.util.datafix.fixes.AttributesRename;
import net.minecraft.util.datafix.fixes.BedItemColorFix;
import net.minecraft.util.datafix.fixes.BiomeFix;
import net.minecraft.util.datafix.fixes.BitStorageAlignFix;
import net.minecraft.util.datafix.fixes.BlendingDataFix;
import net.minecraft.util.datafix.fixes.BlendingDataRemoveFromNetherEndFix;
import net.minecraft.util.datafix.fixes.BlockEntityBannerColorFix;
import net.minecraft.util.datafix.fixes.BlockEntityBlockStateFix;
import net.minecraft.util.datafix.fixes.BlockEntityCustomNameToComponentFix;
import net.minecraft.util.datafix.fixes.BlockEntityIdFix;
import net.minecraft.util.datafix.fixes.BlockEntityJukeboxFix;
import net.minecraft.util.datafix.fixes.BlockEntityKeepPacked;
import net.minecraft.util.datafix.fixes.BlockEntityRenameFix;
import net.minecraft.util.datafix.fixes.BlockEntityShulkerBoxColorFix;
import net.minecraft.util.datafix.fixes.BlockEntitySignDoubleSidedEditableTextFix;
import net.minecraft.util.datafix.fixes.BlockEntitySignTextStrictJsonFix;
import net.minecraft.util.datafix.fixes.BlockEntityUUIDFix;
import net.minecraft.util.datafix.fixes.BlockNameFlatteningFix;
import net.minecraft.util.datafix.fixes.BlockRenameFix;
import net.minecraft.util.datafix.fixes.BlockRenameFixWithJigsaw;
import net.minecraft.util.datafix.fixes.BlockStateStructureTemplateFix;
import net.minecraft.util.datafix.fixes.CatTypeFix;
import net.minecraft.util.datafix.fixes.CauldronRenameFix;
import net.minecraft.util.datafix.fixes.CavesAndCliffsRenames;
import net.minecraft.util.datafix.fixes.ChunkBedBlockEntityInjecterFix;
import net.minecraft.util.datafix.fixes.ChunkBiomeFix;
import net.minecraft.util.datafix.fixes.ChunkDeleteIgnoredLightDataFix;
import net.minecraft.util.datafix.fixes.ChunkDeleteLightFix;
import net.minecraft.util.datafix.fixes.ChunkHeightAndBiomeFix;
import net.minecraft.util.datafix.fixes.ChunkLightRemoveFix;
import net.minecraft.util.datafix.fixes.ChunkPalettedStorageFix;
import net.minecraft.util.datafix.fixes.ChunkProtoTickListFix;
import net.minecraft.util.datafix.fixes.ChunkRenamesFix;
import net.minecraft.util.datafix.fixes.ChunkStatusFix;
import net.minecraft.util.datafix.fixes.ChunkStatusFix2;
import net.minecraft.util.datafix.fixes.ChunkStructuresTemplateRenameFix;
import net.minecraft.util.datafix.fixes.ChunkToProtochunkFix;
import net.minecraft.util.datafix.fixes.ColorlessShulkerEntityFix;
import net.minecraft.util.datafix.fixes.CriteriaRenameFix;
import net.minecraft.util.datafix.fixes.DecoratedPotFieldRenameFix;
import net.minecraft.util.datafix.fixes.DyeItemRenameFix;
import net.minecraft.util.datafix.fixes.EffectDurationFix;
import net.minecraft.util.datafix.fixes.EntityArmorStandSilentFix;
import net.minecraft.util.datafix.fixes.EntityBlockStateFix;
import net.minecraft.util.datafix.fixes.EntityBrushableBlockFieldsRenameFix;
import net.minecraft.util.datafix.fixes.EntityCatSplitFix;
import net.minecraft.util.datafix.fixes.EntityCodSalmonFix;
import net.minecraft.util.datafix.fixes.EntityCustomNameToComponentFix;
import net.minecraft.util.datafix.fixes.EntityElderGuardianSplitFix;
import net.minecraft.util.datafix.fixes.EntityEquipmentToArmorAndHandFix;
import net.minecraft.util.datafix.fixes.EntityGoatMissingStateFix;
import net.minecraft.util.datafix.fixes.EntityHealthFix;
import net.minecraft.util.datafix.fixes.EntityHorseSaddleFix;
import net.minecraft.util.datafix.fixes.EntityHorseSplitFix;
import net.minecraft.util.datafix.fixes.EntityIdFix;
import net.minecraft.util.datafix.fixes.EntityItemFrameDirectionFix;
import net.minecraft.util.datafix.fixes.EntityMinecartIdentifiersFix;
import net.minecraft.util.datafix.fixes.EntityPaintingFieldsRenameFix;
import net.minecraft.util.datafix.fixes.EntityPaintingItemFrameDirectionFix;
import net.minecraft.util.datafix.fixes.EntityPaintingMotiveFix;
import net.minecraft.util.datafix.fixes.EntityProjectileOwnerFix;
import net.minecraft.util.datafix.fixes.EntityPufferfishRenameFix;
import net.minecraft.util.datafix.fixes.EntityRavagerRenameFix;
import net.minecraft.util.datafix.fixes.EntityRedundantChanceTagsFix;
import net.minecraft.util.datafix.fixes.EntityRidingToPassengersFix;
import net.minecraft.util.datafix.fixes.EntityShulkerColorFix;
import net.minecraft.util.datafix.fixes.EntityShulkerRotationFix;
import net.minecraft.util.datafix.fixes.EntitySkeletonSplitFix;
import net.minecraft.util.datafix.fixes.EntityStringUuidFix;
import net.minecraft.util.datafix.fixes.EntityTheRenameningFix;
import net.minecraft.util.datafix.fixes.EntityTippedArrowFix;
import net.minecraft.util.datafix.fixes.EntityUUIDFix;
import net.minecraft.util.datafix.fixes.EntityVariantFix;
import net.minecraft.util.datafix.fixes.EntityWolfColorFix;
import net.minecraft.util.datafix.fixes.EntityZombieSplitFix;
import net.minecraft.util.datafix.fixes.EntityZombieVillagerTypeFix;
import net.minecraft.util.datafix.fixes.EntityZombifiedPiglinRenameFix;
import net.minecraft.util.datafix.fixes.FeatureFlagRemoveFix;
import net.minecraft.util.datafix.fixes.FilteredBooksFix;
import net.minecraft.util.datafix.fixes.FilteredSignsFix;
import net.minecraft.util.datafix.fixes.ForcePoiRebuild;
import net.minecraft.util.datafix.fixes.FurnaceRecipeFix;
import net.minecraft.util.datafix.fixes.GoatHornIdFix;
import net.minecraft.util.datafix.fixes.GossipUUIDFix;
import net.minecraft.util.datafix.fixes.HeightmapRenamingFix;
import net.minecraft.util.datafix.fixes.IglooMetadataRemovalFix;
import net.minecraft.util.datafix.fixes.ItemBannerColorFix;
import net.minecraft.util.datafix.fixes.ItemCustomNameToComponentFix;
import net.minecraft.util.datafix.fixes.ItemIdFix;
import net.minecraft.util.datafix.fixes.ItemLoreFix;
import net.minecraft.util.datafix.fixes.ItemPotionFix;
import net.minecraft.util.datafix.fixes.ItemRemoveBlockEntityTagFix;
import net.minecraft.util.datafix.fixes.ItemRenameFix;
import net.minecraft.util.datafix.fixes.ItemShulkerBoxColorFix;
import net.minecraft.util.datafix.fixes.ItemSpawnEggFix;
import net.minecraft.util.datafix.fixes.ItemStackEnchantmentNamesFix;
import net.minecraft.util.datafix.fixes.ItemStackMapIdFix;
import net.minecraft.util.datafix.fixes.ItemStackSpawnEggFix;
import net.minecraft.util.datafix.fixes.ItemStackTheFlatteningFix;
import net.minecraft.util.datafix.fixes.ItemStackUUIDFix;
import net.minecraft.util.datafix.fixes.ItemWaterPotionFix;
import net.minecraft.util.datafix.fixes.ItemWrittenBookPagesStrictJsonFix;
import net.minecraft.util.datafix.fixes.JigsawPropertiesFix;
import net.minecraft.util.datafix.fixes.JigsawRotationFix;
import net.minecraft.util.datafix.fixes.LeavesFix;
import net.minecraft.util.datafix.fixes.LegacyDragonFightFix;
import net.minecraft.util.datafix.fixes.LevelDataGeneratorOptionsFix;
import net.minecraft.util.datafix.fixes.LevelFlatGeneratorInfoFix;
import net.minecraft.util.datafix.fixes.LevelUUIDFix;
import net.minecraft.util.datafix.fixes.MapIdFix;
import net.minecraft.util.datafix.fixes.MemoryExpiryDataFix;
import net.minecraft.util.datafix.fixes.MissingDimensionFix;
import net.minecraft.util.datafix.fixes.MobSpawnerEntityIdentifiersFix;
import net.minecraft.util.datafix.fixes.NamedEntityFix;
import net.minecraft.util.datafix.fixes.NamespacedTypeRenameFix;
import net.minecraft.util.datafix.fixes.NewVillageFix;
import net.minecraft.util.datafix.fixes.ObjectiveDisplayNameFix;
import net.minecraft.util.datafix.fixes.ObjectiveRenderTypeFix;
import net.minecraft.util.datafix.fixes.OminousBannerBlockEntityRenameFix;
import net.minecraft.util.datafix.fixes.OminousBannerRenameFix;
import net.minecraft.util.datafix.fixes.OptionsAccessibilityOnboardFix;
import net.minecraft.util.datafix.fixes.OptionsAddTextBackgroundFix;
import net.minecraft.util.datafix.fixes.OptionsAmbientOcclusionFix;
import net.minecraft.util.datafix.fixes.OptionsForceVBOFix;
import net.minecraft.util.datafix.fixes.OptionsKeyLwjgl3Fix;
import net.minecraft.util.datafix.fixes.OptionsKeyTranslationFix;
import net.minecraft.util.datafix.fixes.OptionsLowerCaseLanguageFix;
import net.minecraft.util.datafix.fixes.OptionsProgrammerArtFix;
import net.minecraft.util.datafix.fixes.OptionsRenameFieldFix;
import net.minecraft.util.datafix.fixes.OverreachingTickFix;
import net.minecraft.util.datafix.fixes.PlayerUUIDFix;
import net.minecraft.util.datafix.fixes.PoiTypeRemoveFix;
import net.minecraft.util.datafix.fixes.PoiTypeRenameFix;
import net.minecraft.util.datafix.fixes.RecipesFix;
import net.minecraft.util.datafix.fixes.RecipesRenameningFix;
import net.minecraft.util.datafix.fixes.RedstoneWireConnectionsFix;
import net.minecraft.util.datafix.fixes.References;
import net.minecraft.util.datafix.fixes.RemapChunkStatusFix;
import net.minecraft.util.datafix.fixes.RemoveGolemGossipFix;
import net.minecraft.util.datafix.fixes.RenamedCoralFansFix;
import net.minecraft.util.datafix.fixes.RenamedCoralFix;
import net.minecraft.util.datafix.fixes.ReorganizePoi;
import net.minecraft.util.datafix.fixes.SavedDataFeaturePoolElementFix;
import net.minecraft.util.datafix.fixes.SavedDataUUIDFix;
import net.minecraft.util.datafix.fixes.SpawnerDataFix;
import net.minecraft.util.datafix.fixes.StatsCounterFix;
import net.minecraft.util.datafix.fixes.StatsRenameFix;
import net.minecraft.util.datafix.fixes.StriderGravityFix;
import net.minecraft.util.datafix.fixes.StructureReferenceCountFix;
import net.minecraft.util.datafix.fixes.StructureSettingsFlattenFix;
import net.minecraft.util.datafix.fixes.StructuresBecomeConfiguredFix;
import net.minecraft.util.datafix.fixes.TeamDisplayNameFix;
import net.minecraft.util.datafix.fixes.TrappedChestBlockEntityFix;
import net.minecraft.util.datafix.fixes.VariantRenameFix;
import net.minecraft.util.datafix.fixes.VillagerDataFix;
import net.minecraft.util.datafix.fixes.VillagerFollowRangeFix;
import net.minecraft.util.datafix.fixes.VillagerRebuildLevelAndXpFix;
import net.minecraft.util.datafix.fixes.VillagerTradeFix;
import net.minecraft.util.datafix.fixes.WallPropertyFix;
import net.minecraft.util.datafix.fixes.WeaponSmithChestLootTableFix;
import net.minecraft.util.datafix.fixes.WorldGenSettingsDisallowOldCustomWorldsFix;
import net.minecraft.util.datafix.fixes.WorldGenSettingsFix;
import net.minecraft.util.datafix.fixes.WorldGenSettingsHeightAndBiomeFix;
import net.minecraft.util.datafix.fixes.WriteAndReadFix;
import net.minecraft.util.datafix.fixes.ZombieVillagerRebuildXpFix;
import net.minecraft.util.datafix.schemas.NamespacedSchema;
import net.minecraft.util.datafix.schemas.V100;
import net.minecraft.util.datafix.schemas.V102;
import net.minecraft.util.datafix.schemas.V1022;
import net.minecraft.util.datafix.schemas.V106;
import net.minecraft.util.datafix.schemas.V107;
import net.minecraft.util.datafix.schemas.V1125;
import net.minecraft.util.datafix.schemas.V135;
import net.minecraft.util.datafix.schemas.V143;
import net.minecraft.util.datafix.schemas.V1451;
import net.minecraft.util.datafix.schemas.V1451_1;
import net.minecraft.util.datafix.schemas.V1451_2;
import net.minecraft.util.datafix.schemas.V1451_3;
import net.minecraft.util.datafix.schemas.V1451_4;
import net.minecraft.util.datafix.schemas.V1451_5;
import net.minecraft.util.datafix.schemas.V1451_6;
import net.minecraft.util.datafix.schemas.V1460;
import net.minecraft.util.datafix.schemas.V1466;
import net.minecraft.util.datafix.schemas.V1470;
import net.minecraft.util.datafix.schemas.V1481;
import net.minecraft.util.datafix.schemas.V1483;
import net.minecraft.util.datafix.schemas.V1486;
import net.minecraft.util.datafix.schemas.V1510;
import net.minecraft.util.datafix.schemas.V1800;
import net.minecraft.util.datafix.schemas.V1801;
import net.minecraft.util.datafix.schemas.V1904;
import net.minecraft.util.datafix.schemas.V1906;
import net.minecraft.util.datafix.schemas.V1909;
import net.minecraft.util.datafix.schemas.V1920;
import net.minecraft.util.datafix.schemas.V1928;
import net.minecraft.util.datafix.schemas.V1929;
import net.minecraft.util.datafix.schemas.V1931;
import net.minecraft.util.datafix.schemas.V2100;
import net.minecraft.util.datafix.schemas.V2501;
import net.minecraft.util.datafix.schemas.V2502;
import net.minecraft.util.datafix.schemas.V2505;
import net.minecraft.util.datafix.schemas.V2509;
import net.minecraft.util.datafix.schemas.V2519;
import net.minecraft.util.datafix.schemas.V2522;
import net.minecraft.util.datafix.schemas.V2551;
import net.minecraft.util.datafix.schemas.V2568;
import net.minecraft.util.datafix.schemas.V2571;
import net.minecraft.util.datafix.schemas.V2684;
import net.minecraft.util.datafix.schemas.V2686;
import net.minecraft.util.datafix.schemas.V2688;
import net.minecraft.util.datafix.schemas.V2704;
import net.minecraft.util.datafix.schemas.V2707;
import net.minecraft.util.datafix.schemas.V2831;
import net.minecraft.util.datafix.schemas.V2832;
import net.minecraft.util.datafix.schemas.V2842;
import net.minecraft.util.datafix.schemas.V3076;
import net.minecraft.util.datafix.schemas.V3078;
import net.minecraft.util.datafix.schemas.V3081;
import net.minecraft.util.datafix.schemas.V3082;
import net.minecraft.util.datafix.schemas.V3083;
import net.minecraft.util.datafix.schemas.V3202;
import net.minecraft.util.datafix.schemas.V3203;
import net.minecraft.util.datafix.schemas.V3204;
import net.minecraft.util.datafix.schemas.V3325;
import net.minecraft.util.datafix.schemas.V3326;
import net.minecraft.util.datafix.schemas.V3327;
import net.minecraft.util.datafix.schemas.V3328;
import net.minecraft.util.datafix.schemas.V3438;
import net.minecraft.util.datafix.schemas.V3448;
import net.minecraft.util.datafix.schemas.V501;
import net.minecraft.util.datafix.schemas.V700;
import net.minecraft.util.datafix.schemas.V701;
import net.minecraft.util.datafix.schemas.V702;
import net.minecraft.util.datafix.schemas.V703;
import net.minecraft.util.datafix.schemas.V704;
import net.minecraft.util.datafix.schemas.V705;
import net.minecraft.util.datafix.schemas.V808;
import net.minecraft.util.datafix.schemas.V99;

public class DataFixers {

    private static final BiFunction<Integer, Schema, Schema> SAME = Schema::new;

    private static final BiFunction<Integer, Schema, Schema> SAME_NAMESPACED = NamespacedSchema::new;

    private static final DataFixer dataFixer = createFixerUpper(SharedConstants.DATA_FIX_TYPES_TO_OPTIMIZE);

    public static final int BLENDING_VERSION = 3441;

    private DataFixers() {
    }

    public static DataFixer getDataFixer() {
        return dataFixer;
    }

    private static synchronized DataFixer createFixerUpper(Set<TypeReference> setTypeReference0) {
        DataFixerBuilder $$1 = new DataFixerBuilder(SharedConstants.getCurrentVersion().getDataVersion().getVersion());
        addFixers($$1);
        if (setTypeReference0.isEmpty()) {
            return $$1.buildUnoptimized();
        } else {
            Executor $$2 = Executors.newSingleThreadExecutor(new ThreadFactoryBuilder().setNameFormat("Datafixer Bootstrap").setDaemon(true).setPriority(1).build());
            return $$1.buildOptimized(setTypeReference0, $$2);
        }
    }

    private static void addFixers(DataFixerBuilder dataFixerBuilder0) {
        dataFixerBuilder0.addSchema(99, V99::new);
        Schema $$1 = dataFixerBuilder0.addSchema(100, V100::new);
        dataFixerBuilder0.addFixer(new EntityEquipmentToArmorAndHandFix($$1, true));
        Schema $$2 = dataFixerBuilder0.addSchema(101, SAME);
        dataFixerBuilder0.addFixer(new BlockEntitySignTextStrictJsonFix($$2, false));
        Schema $$3 = dataFixerBuilder0.addSchema(102, V102::new);
        dataFixerBuilder0.addFixer(new ItemIdFix($$3, true));
        dataFixerBuilder0.addFixer(new ItemPotionFix($$3, false));
        Schema $$4 = dataFixerBuilder0.addSchema(105, SAME);
        dataFixerBuilder0.addFixer(new ItemSpawnEggFix($$4, true));
        Schema $$5 = dataFixerBuilder0.addSchema(106, V106::new);
        dataFixerBuilder0.addFixer(new MobSpawnerEntityIdentifiersFix($$5, true));
        Schema $$6 = dataFixerBuilder0.addSchema(107, V107::new);
        dataFixerBuilder0.addFixer(new EntityMinecartIdentifiersFix($$6, true));
        Schema $$7 = dataFixerBuilder0.addSchema(108, SAME);
        dataFixerBuilder0.addFixer(new EntityStringUuidFix($$7, true));
        Schema $$8 = dataFixerBuilder0.addSchema(109, SAME);
        dataFixerBuilder0.addFixer(new EntityHealthFix($$8, true));
        Schema $$9 = dataFixerBuilder0.addSchema(110, SAME);
        dataFixerBuilder0.addFixer(new EntityHorseSaddleFix($$9, true));
        Schema $$10 = dataFixerBuilder0.addSchema(111, SAME);
        dataFixerBuilder0.addFixer(new EntityPaintingItemFrameDirectionFix($$10, true));
        Schema $$11 = dataFixerBuilder0.addSchema(113, SAME);
        dataFixerBuilder0.addFixer(new EntityRedundantChanceTagsFix($$11, true));
        Schema $$12 = dataFixerBuilder0.addSchema(135, V135::new);
        dataFixerBuilder0.addFixer(new EntityRidingToPassengersFix($$12, true));
        Schema $$13 = dataFixerBuilder0.addSchema(143, V143::new);
        dataFixerBuilder0.addFixer(new EntityTippedArrowFix($$13, true));
        Schema $$14 = dataFixerBuilder0.addSchema(147, SAME);
        dataFixerBuilder0.addFixer(new EntityArmorStandSilentFix($$14, true));
        Schema $$15 = dataFixerBuilder0.addSchema(165, SAME);
        dataFixerBuilder0.addFixer(new ItemWrittenBookPagesStrictJsonFix($$15, true));
        Schema $$16 = dataFixerBuilder0.addSchema(501, V501::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$16, "Add 1.10 entities fix", References.ENTITY));
        Schema $$17 = dataFixerBuilder0.addSchema(502, SAME);
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$17, "cooked_fished item renamer", p_14533_ -> Objects.equals(NamespacedSchema.ensureNamespaced(p_14533_), "minecraft:cooked_fished") ? "minecraft:cooked_fish" : p_14533_));
        dataFixerBuilder0.addFixer(new EntityZombieVillagerTypeFix($$17, false));
        Schema $$18 = dataFixerBuilder0.addSchema(505, SAME);
        dataFixerBuilder0.addFixer(new OptionsForceVBOFix($$18, false));
        Schema $$19 = dataFixerBuilder0.addSchema(700, V700::new);
        dataFixerBuilder0.addFixer(new EntityElderGuardianSplitFix($$19, true));
        Schema $$20 = dataFixerBuilder0.addSchema(701, V701::new);
        dataFixerBuilder0.addFixer(new EntitySkeletonSplitFix($$20, true));
        Schema $$21 = dataFixerBuilder0.addSchema(702, V702::new);
        dataFixerBuilder0.addFixer(new EntityZombieSplitFix($$21, true));
        Schema $$22 = dataFixerBuilder0.addSchema(703, V703::new);
        dataFixerBuilder0.addFixer(new EntityHorseSplitFix($$22, true));
        Schema $$23 = dataFixerBuilder0.addSchema(704, V704::new);
        dataFixerBuilder0.addFixer(new BlockEntityIdFix($$23, true));
        Schema $$24 = dataFixerBuilder0.addSchema(705, V705::new);
        dataFixerBuilder0.addFixer(new EntityIdFix($$24, true));
        Schema $$25 = dataFixerBuilder0.addSchema(804, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new ItemBannerColorFix($$25, true));
        Schema $$26 = dataFixerBuilder0.addSchema(806, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new ItemWaterPotionFix($$26, false));
        Schema $$27 = dataFixerBuilder0.addSchema(808, V808::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$27, "added shulker box", References.BLOCK_ENTITY));
        Schema $$28 = dataFixerBuilder0.addSchema(808, 1, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new EntityShulkerColorFix($$28, false));
        Schema $$29 = dataFixerBuilder0.addSchema(813, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new ItemShulkerBoxColorFix($$29, false));
        dataFixerBuilder0.addFixer(new BlockEntityShulkerBoxColorFix($$29, false));
        Schema $$30 = dataFixerBuilder0.addSchema(816, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new OptionsLowerCaseLanguageFix($$30, false));
        Schema $$31 = dataFixerBuilder0.addSchema(820, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$31, "totem item renamer", createRenamer("minecraft:totem", "minecraft:totem_of_undying")));
        Schema $$32 = dataFixerBuilder0.addSchema(1022, V1022::new);
        dataFixerBuilder0.addFixer(new WriteAndReadFix($$32, "added shoulder entities to players", References.PLAYER));
        Schema $$33 = dataFixerBuilder0.addSchema(1125, V1125::new);
        dataFixerBuilder0.addFixer(new ChunkBedBlockEntityInjecterFix($$33, true));
        dataFixerBuilder0.addFixer(new BedItemColorFix($$33, false));
        Schema $$34 = dataFixerBuilder0.addSchema(1344, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new OptionsKeyLwjgl3Fix($$34, false));
        Schema $$35 = dataFixerBuilder0.addSchema(1446, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new OptionsKeyTranslationFix($$35, false));
        Schema $$36 = dataFixerBuilder0.addSchema(1450, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new BlockStateStructureTemplateFix($$36, false));
        Schema $$37 = dataFixerBuilder0.addSchema(1451, V1451::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$37, "AddTrappedChestFix", References.BLOCK_ENTITY));
        Schema $$38 = dataFixerBuilder0.addSchema(1451, 1, V1451_1::new);
        dataFixerBuilder0.addFixer(new ChunkPalettedStorageFix($$38, true));
        Schema $$39 = dataFixerBuilder0.addSchema(1451, 2, V1451_2::new);
        dataFixerBuilder0.addFixer(new BlockEntityBlockStateFix($$39, true));
        Schema $$40 = dataFixerBuilder0.addSchema(1451, 3, V1451_3::new);
        dataFixerBuilder0.addFixer(new EntityBlockStateFix($$40, true));
        dataFixerBuilder0.addFixer(new ItemStackMapIdFix($$40, false));
        Schema $$41 = dataFixerBuilder0.addSchema(1451, 4, V1451_4::new);
        dataFixerBuilder0.addFixer(new BlockNameFlatteningFix($$41, true));
        dataFixerBuilder0.addFixer(new ItemStackTheFlatteningFix($$41, false));
        Schema $$42 = dataFixerBuilder0.addSchema(1451, 5, V1451_5::new);
        dataFixerBuilder0.addFixer(new ItemRemoveBlockEntityTagFix($$42, false, Set.of("minecraft:note_block", "minecraft:flower_pot", "minecraft:dandelion", "minecraft:poppy", "minecraft:blue_orchid", "minecraft:allium", "minecraft:azure_bluet", "minecraft:red_tulip", "minecraft:orange_tulip", "minecraft:white_tulip", "minecraft:pink_tulip", "minecraft:oxeye_daisy", "minecraft:cactus", "minecraft:brown_mushroom", "minecraft:red_mushroom", "minecraft:oak_sapling", "minecraft:spruce_sapling", "minecraft:birch_sapling", "minecraft:jungle_sapling", "minecraft:acacia_sapling", "minecraft:dark_oak_sapling", "minecraft:dead_bush", "minecraft:fern")));
        dataFixerBuilder0.addFixer(new AddNewChoices($$42, "RemoveNoteBlockFlowerPotFix", References.BLOCK_ENTITY));
        dataFixerBuilder0.addFixer(new ItemStackSpawnEggFix($$42, false, "minecraft:spawn_egg"));
        dataFixerBuilder0.addFixer(new EntityWolfColorFix($$42, false));
        dataFixerBuilder0.addFixer(new BlockEntityBannerColorFix($$42, false));
        dataFixerBuilder0.addFixer(new LevelFlatGeneratorInfoFix($$42, false));
        Schema $$43 = dataFixerBuilder0.addSchema(1451, 6, V1451_6::new);
        dataFixerBuilder0.addFixer(new StatsCounterFix($$43, true));
        dataFixerBuilder0.addFixer(new WriteAndReadFix($$43, "Rewrite objectives", References.OBJECTIVE));
        dataFixerBuilder0.addFixer(new BlockEntityJukeboxFix($$43, false));
        Schema $$44 = dataFixerBuilder0.addSchema(1451, 7, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new VillagerTradeFix($$44, false));
        Schema $$45 = dataFixerBuilder0.addSchema(1456, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new EntityItemFrameDirectionFix($$45, false));
        Schema $$46 = dataFixerBuilder0.addSchema(1458, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new EntityCustomNameToComponentFix($$46, false));
        dataFixerBuilder0.addFixer(new ItemCustomNameToComponentFix($$46, false));
        dataFixerBuilder0.addFixer(new BlockEntityCustomNameToComponentFix($$46, false));
        Schema $$47 = dataFixerBuilder0.addSchema(1460, V1460::new);
        dataFixerBuilder0.addFixer(new EntityPaintingMotiveFix($$47, false));
        Schema $$48 = dataFixerBuilder0.addSchema(1466, V1466::new);
        dataFixerBuilder0.addFixer(new ChunkToProtochunkFix($$48, true));
        Schema $$49 = dataFixerBuilder0.addSchema(1470, V1470::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$49, "Add 1.13 entities fix", References.ENTITY));
        Schema $$50 = dataFixerBuilder0.addSchema(1474, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new ColorlessShulkerEntityFix($$50, false));
        dataFixerBuilder0.addFixer(BlockRenameFix.create($$50, "Colorless shulker block fixer", p_14531_ -> Objects.equals(NamespacedSchema.ensureNamespaced(p_14531_), "minecraft:purple_shulker_box") ? "minecraft:shulker_box" : p_14531_));
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$50, "Colorless shulker item fixer", p_14516_ -> Objects.equals(NamespacedSchema.ensureNamespaced(p_14516_), "minecraft:purple_shulker_box") ? "minecraft:shulker_box" : p_14516_));
        Schema $$51 = dataFixerBuilder0.addSchema(1475, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(BlockRenameFix.create($$51, "Flowing fixer", createRenamer(ImmutableMap.of("minecraft:flowing_water", "minecraft:water", "minecraft:flowing_lava", "minecraft:lava"))));
        Schema $$52 = dataFixerBuilder0.addSchema(1480, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(BlockRenameFix.create($$52, "Rename coral blocks", createRenamer(RenamedCoralFix.RENAMED_IDS)));
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$52, "Rename coral items", createRenamer(RenamedCoralFix.RENAMED_IDS)));
        Schema $$53 = dataFixerBuilder0.addSchema(1481, V1481::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$53, "Add conduit", References.BLOCK_ENTITY));
        Schema $$54 = dataFixerBuilder0.addSchema(1483, V1483::new);
        dataFixerBuilder0.addFixer(new EntityPufferfishRenameFix($$54, true));
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$54, "Rename pufferfish egg item", createRenamer(EntityPufferfishRenameFix.RENAMED_IDS)));
        Schema $$55 = dataFixerBuilder0.addSchema(1484, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$55, "Rename seagrass items", createRenamer(ImmutableMap.of("minecraft:sea_grass", "minecraft:seagrass", "minecraft:tall_sea_grass", "minecraft:tall_seagrass"))));
        dataFixerBuilder0.addFixer(BlockRenameFix.create($$55, "Rename seagrass blocks", createRenamer(ImmutableMap.of("minecraft:sea_grass", "minecraft:seagrass", "minecraft:tall_sea_grass", "minecraft:tall_seagrass"))));
        dataFixerBuilder0.addFixer(new HeightmapRenamingFix($$55, false));
        Schema $$56 = dataFixerBuilder0.addSchema(1486, V1486::new);
        dataFixerBuilder0.addFixer(new EntityCodSalmonFix($$56, true));
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$56, "Rename cod/salmon egg items", createRenamer(EntityCodSalmonFix.RENAMED_EGG_IDS)));
        Schema $$57 = dataFixerBuilder0.addSchema(1487, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$57, "Rename prismarine_brick(s)_* blocks", createRenamer(ImmutableMap.of("minecraft:prismarine_bricks_slab", "minecraft:prismarine_brick_slab", "minecraft:prismarine_bricks_stairs", "minecraft:prismarine_brick_stairs"))));
        dataFixerBuilder0.addFixer(BlockRenameFix.create($$57, "Rename prismarine_brick(s)_* items", createRenamer(ImmutableMap.of("minecraft:prismarine_bricks_slab", "minecraft:prismarine_brick_slab", "minecraft:prismarine_bricks_stairs", "minecraft:prismarine_brick_stairs"))));
        Schema $$58 = dataFixerBuilder0.addSchema(1488, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(BlockRenameFix.create($$58, "Rename kelp/kelptop", createRenamer(ImmutableMap.of("minecraft:kelp_top", "minecraft:kelp", "minecraft:kelp", "minecraft:kelp_plant"))));
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$58, "Rename kelptop", createRenamer("minecraft:kelp_top", "minecraft:kelp")));
        dataFixerBuilder0.addFixer(new NamedEntityFix($$58, false, "Command block block entity custom name fix", References.BLOCK_ENTITY, "minecraft:command_block") {

            @Override
            protected Typed<?> fix(Typed<?> p_14541_) {
                return p_14541_.update(DSL.remainderFinder(), EntityCustomNameToComponentFix::m_15407_);
            }
        });
        dataFixerBuilder0.addFixer(new NamedEntityFix($$58, false, "Command block minecart custom name fix", References.ENTITY, "minecraft:commandblock_minecart") {

            @Override
            protected Typed<?> fix(Typed<?> p_14549_) {
                return p_14549_.update(DSL.remainderFinder(), EntityCustomNameToComponentFix::m_15407_);
            }
        });
        dataFixerBuilder0.addFixer(new IglooMetadataRemovalFix($$58, false));
        Schema $$59 = dataFixerBuilder0.addSchema(1490, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(BlockRenameFix.create($$59, "Rename melon_block", createRenamer("minecraft:melon_block", "minecraft:melon")));
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$59, "Rename melon_block/melon/speckled_melon", createRenamer(ImmutableMap.of("minecraft:melon_block", "minecraft:melon", "minecraft:melon", "minecraft:melon_slice", "minecraft:speckled_melon", "minecraft:glistering_melon_slice"))));
        Schema $$60 = dataFixerBuilder0.addSchema(1492, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new ChunkStructuresTemplateRenameFix($$60, false));
        Schema $$61 = dataFixerBuilder0.addSchema(1494, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new ItemStackEnchantmentNamesFix($$61, false));
        Schema $$62 = dataFixerBuilder0.addSchema(1496, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new LeavesFix($$62, false));
        Schema $$63 = dataFixerBuilder0.addSchema(1500, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new BlockEntityKeepPacked($$63, false));
        Schema $$64 = dataFixerBuilder0.addSchema(1501, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new AdvancementsFix($$64, false));
        Schema $$65 = dataFixerBuilder0.addSchema(1502, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new NamespacedTypeRenameFix($$65, "Recipes fix", References.RECIPE, createRenamer(RecipesFix.RECIPES)));
        Schema $$66 = dataFixerBuilder0.addSchema(1506, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new LevelDataGeneratorOptionsFix($$66, false));
        Schema $$67 = dataFixerBuilder0.addSchema(1510, V1510::new);
        dataFixerBuilder0.addFixer(BlockRenameFix.create($$67, "Block renamening fix", createRenamer(EntityTheRenameningFix.RENAMED_BLOCKS)));
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$67, "Item renamening fix", createRenamer(EntityTheRenameningFix.RENAMED_ITEMS)));
        dataFixerBuilder0.addFixer(new NamespacedTypeRenameFix($$67, "Recipes renamening fix", References.RECIPE, createRenamer(RecipesRenameningFix.RECIPES)));
        dataFixerBuilder0.addFixer(new EntityTheRenameningFix($$67, true));
        dataFixerBuilder0.addFixer(new StatsRenameFix($$67, "SwimStatsRenameFix", ImmutableMap.of("minecraft:swim_one_cm", "minecraft:walk_on_water_one_cm", "minecraft:dive_one_cm", "minecraft:walk_under_water_one_cm")));
        Schema $$68 = dataFixerBuilder0.addSchema(1514, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new ObjectiveDisplayNameFix($$68, false));
        dataFixerBuilder0.addFixer(new TeamDisplayNameFix($$68, false));
        dataFixerBuilder0.addFixer(new ObjectiveRenderTypeFix($$68, false));
        Schema $$69 = dataFixerBuilder0.addSchema(1515, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(BlockRenameFix.create($$69, "Rename coral fan blocks", createRenamer(RenamedCoralFansFix.RENAMED_IDS)));
        Schema $$70 = dataFixerBuilder0.addSchema(1624, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new TrappedChestBlockEntityFix($$70, false));
        Schema $$71 = dataFixerBuilder0.addSchema(1800, V1800::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$71, "Added 1.14 mobs fix", References.ENTITY));
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$71, "Rename dye items", createRenamer(DyeItemRenameFix.RENAMED_IDS)));
        Schema $$72 = dataFixerBuilder0.addSchema(1801, V1801::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$72, "Added Illager Beast", References.ENTITY));
        Schema $$73 = dataFixerBuilder0.addSchema(1802, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(BlockRenameFix.create($$73, "Rename sign blocks & stone slabs", createRenamer(ImmutableMap.of("minecraft:stone_slab", "minecraft:smooth_stone_slab", "minecraft:sign", "minecraft:oak_sign", "minecraft:wall_sign", "minecraft:oak_wall_sign"))));
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$73, "Rename sign item & stone slabs", createRenamer(ImmutableMap.of("minecraft:stone_slab", "minecraft:smooth_stone_slab", "minecraft:sign", "minecraft:oak_sign"))));
        Schema $$74 = dataFixerBuilder0.addSchema(1803, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new ItemLoreFix($$74, false));
        Schema $$75 = dataFixerBuilder0.addSchema(1904, V1904::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$75, "Added Cats", References.ENTITY));
        dataFixerBuilder0.addFixer(new EntityCatSplitFix($$75, false));
        Schema $$76 = dataFixerBuilder0.addSchema(1905, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new ChunkStatusFix($$76, false));
        Schema $$77 = dataFixerBuilder0.addSchema(1906, V1906::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$77, "Add POI Blocks", References.BLOCK_ENTITY));
        Schema $$78 = dataFixerBuilder0.addSchema(1909, V1909::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$78, "Add jigsaw", References.BLOCK_ENTITY));
        Schema $$79 = dataFixerBuilder0.addSchema(1911, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new ChunkStatusFix2($$79, false));
        Schema $$80 = dataFixerBuilder0.addSchema(1914, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new WeaponSmithChestLootTableFix($$80, false));
        Schema $$81 = dataFixerBuilder0.addSchema(1917, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new CatTypeFix($$81, false));
        Schema $$82 = dataFixerBuilder0.addSchema(1918, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new VillagerDataFix($$82, "minecraft:villager"));
        dataFixerBuilder0.addFixer(new VillagerDataFix($$82, "minecraft:zombie_villager"));
        Schema $$83 = dataFixerBuilder0.addSchema(1920, V1920::new);
        dataFixerBuilder0.addFixer(new NewVillageFix($$83, false));
        dataFixerBuilder0.addFixer(new AddNewChoices($$83, "Add campfire", References.BLOCK_ENTITY));
        Schema $$84 = dataFixerBuilder0.addSchema(1925, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new MapIdFix($$84, false));
        Schema $$85 = dataFixerBuilder0.addSchema(1928, V1928::new);
        dataFixerBuilder0.addFixer(new EntityRavagerRenameFix($$85, true));
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$85, "Rename ravager egg item", createRenamer(EntityRavagerRenameFix.RENAMED_IDS)));
        Schema $$86 = dataFixerBuilder0.addSchema(1929, V1929::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$86, "Add Wandering Trader and Trader Llama", References.ENTITY));
        Schema $$87 = dataFixerBuilder0.addSchema(1931, V1931::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$87, "Added Fox", References.ENTITY));
        Schema $$88 = dataFixerBuilder0.addSchema(1936, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new OptionsAddTextBackgroundFix($$88, false));
        Schema $$89 = dataFixerBuilder0.addSchema(1946, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new ReorganizePoi($$89, false));
        Schema $$90 = dataFixerBuilder0.addSchema(1948, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new OminousBannerRenameFix($$90));
        Schema $$91 = dataFixerBuilder0.addSchema(1953, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new OminousBannerBlockEntityRenameFix($$91, false));
        Schema $$92 = dataFixerBuilder0.addSchema(1955, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new VillagerRebuildLevelAndXpFix($$92, false));
        dataFixerBuilder0.addFixer(new ZombieVillagerRebuildXpFix($$92, false));
        Schema $$93 = dataFixerBuilder0.addSchema(1961, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new ChunkLightRemoveFix($$93, false));
        Schema $$94 = dataFixerBuilder0.addSchema(1963, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new RemoveGolemGossipFix($$94, false));
        Schema $$95 = dataFixerBuilder0.addSchema(2100, V2100::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$95, "Added Bee and Bee Stinger", References.ENTITY));
        dataFixerBuilder0.addFixer(new AddNewChoices($$95, "Add beehive", References.BLOCK_ENTITY));
        dataFixerBuilder0.addFixer(new NamespacedTypeRenameFix($$95, "Rename sugar recipe", References.RECIPE, createRenamer("minecraft:sugar", "sugar_from_sugar_cane")));
        dataFixerBuilder0.addFixer(new AdvancementsRenameFix($$95, false, "Rename sugar recipe advancement", createRenamer("minecraft:recipes/misc/sugar", "minecraft:recipes/misc/sugar_from_sugar_cane")));
        Schema $$96 = dataFixerBuilder0.addSchema(2202, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new ChunkBiomeFix($$96, false));
        Schema $$97 = dataFixerBuilder0.addSchema(2209, SAME_NAMESPACED);
        UnaryOperator<String> $$98 = createRenamer("minecraft:bee_hive", "minecraft:beehive");
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$97, "Rename bee_hive item to beehive", $$98));
        dataFixerBuilder0.addFixer(new PoiTypeRenameFix($$97, "Rename bee_hive poi to beehive", $$98));
        dataFixerBuilder0.addFixer(BlockRenameFix.create($$97, "Rename bee_hive block to beehive", $$98));
        Schema $$99 = dataFixerBuilder0.addSchema(2211, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new StructureReferenceCountFix($$99, false));
        Schema $$100 = dataFixerBuilder0.addSchema(2218, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new ForcePoiRebuild($$100, false));
        Schema $$101 = dataFixerBuilder0.addSchema(2501, V2501::new);
        dataFixerBuilder0.addFixer(new FurnaceRecipeFix($$101, true));
        Schema $$102 = dataFixerBuilder0.addSchema(2502, V2502::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$102, "Added Hoglin", References.ENTITY));
        Schema $$103 = dataFixerBuilder0.addSchema(2503, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new WallPropertyFix($$103, false));
        dataFixerBuilder0.addFixer(new AdvancementsRenameFix($$103, false, "Composter category change", createRenamer("minecraft:recipes/misc/composter", "minecraft:recipes/decorations/composter")));
        Schema $$104 = dataFixerBuilder0.addSchema(2505, V2505::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$104, "Added Piglin", References.ENTITY));
        dataFixerBuilder0.addFixer(new MemoryExpiryDataFix($$104, "minecraft:villager"));
        Schema $$105 = dataFixerBuilder0.addSchema(2508, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$105, "Renamed fungi items to fungus", createRenamer(ImmutableMap.of("minecraft:warped_fungi", "minecraft:warped_fungus", "minecraft:crimson_fungi", "minecraft:crimson_fungus"))));
        dataFixerBuilder0.addFixer(BlockRenameFix.create($$105, "Renamed fungi blocks to fungus", createRenamer(ImmutableMap.of("minecraft:warped_fungi", "minecraft:warped_fungus", "minecraft:crimson_fungi", "minecraft:crimson_fungus"))));
        Schema $$106 = dataFixerBuilder0.addSchema(2509, V2509::new);
        dataFixerBuilder0.addFixer(new EntityZombifiedPiglinRenameFix($$106));
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$106, "Rename zombie pigman egg item", createRenamer(EntityZombifiedPiglinRenameFix.RENAMED_IDS)));
        Schema $$107 = dataFixerBuilder0.addSchema(2511, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new EntityProjectileOwnerFix($$107));
        Schema $$108 = dataFixerBuilder0.addSchema(2514, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new EntityUUIDFix($$108));
        dataFixerBuilder0.addFixer(new BlockEntityUUIDFix($$108));
        dataFixerBuilder0.addFixer(new PlayerUUIDFix($$108));
        dataFixerBuilder0.addFixer(new LevelUUIDFix($$108));
        dataFixerBuilder0.addFixer(new SavedDataUUIDFix($$108));
        dataFixerBuilder0.addFixer(new ItemStackUUIDFix($$108));
        Schema $$109 = dataFixerBuilder0.addSchema(2516, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new GossipUUIDFix($$109, "minecraft:villager"));
        dataFixerBuilder0.addFixer(new GossipUUIDFix($$109, "minecraft:zombie_villager"));
        Schema $$110 = dataFixerBuilder0.addSchema(2518, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new JigsawPropertiesFix($$110, false));
        dataFixerBuilder0.addFixer(new JigsawRotationFix($$110, false));
        Schema $$111 = dataFixerBuilder0.addSchema(2519, V2519::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$111, "Added Strider", References.ENTITY));
        Schema $$112 = dataFixerBuilder0.addSchema(2522, V2522::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$112, "Added Zoglin", References.ENTITY));
        Schema $$113 = dataFixerBuilder0.addSchema(2523, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new AttributesRename($$113));
        Schema $$114 = dataFixerBuilder0.addSchema(2527, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new BitStorageAlignFix($$114));
        Schema $$115 = dataFixerBuilder0.addSchema(2528, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$115, "Rename soul fire torch and soul fire lantern", createRenamer(ImmutableMap.of("minecraft:soul_fire_torch", "minecraft:soul_torch", "minecraft:soul_fire_lantern", "minecraft:soul_lantern"))));
        dataFixerBuilder0.addFixer(BlockRenameFix.create($$115, "Rename soul fire torch and soul fire lantern", createRenamer(ImmutableMap.of("minecraft:soul_fire_torch", "minecraft:soul_torch", "minecraft:soul_fire_wall_torch", "minecraft:soul_wall_torch", "minecraft:soul_fire_lantern", "minecraft:soul_lantern"))));
        Schema $$116 = dataFixerBuilder0.addSchema(2529, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new StriderGravityFix($$116, false));
        Schema $$117 = dataFixerBuilder0.addSchema(2531, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new RedstoneWireConnectionsFix($$117));
        Schema $$118 = dataFixerBuilder0.addSchema(2533, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new VillagerFollowRangeFix($$118));
        Schema $$119 = dataFixerBuilder0.addSchema(2535, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new EntityShulkerRotationFix($$119));
        Schema $$120 = dataFixerBuilder0.addSchema(2550, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new WorldGenSettingsFix($$120));
        Schema $$121 = dataFixerBuilder0.addSchema(2551, V2551::new);
        dataFixerBuilder0.addFixer(new WriteAndReadFix($$121, "add types to WorldGenData", References.WORLD_GEN_SETTINGS));
        Schema $$122 = dataFixerBuilder0.addSchema(2552, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new NamespacedTypeRenameFix($$122, "Nether biome rename", References.BIOME, createRenamer("minecraft:nether", "minecraft:nether_wastes")));
        Schema $$123 = dataFixerBuilder0.addSchema(2553, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new NamespacedTypeRenameFix($$123, "Biomes fix", References.BIOME, createRenamer(BiomeFix.BIOMES)));
        Schema $$124 = dataFixerBuilder0.addSchema(2558, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new MissingDimensionFix($$124, false));
        dataFixerBuilder0.addFixer(new OptionsRenameFieldFix($$124, false, "Rename swapHands setting", "key_key.swapHands", "key_key.swapOffhand"));
        Schema $$125 = dataFixerBuilder0.addSchema(2568, V2568::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$125, "Added Piglin Brute", References.ENTITY));
        Schema $$126 = dataFixerBuilder0.addSchema(2571, V2571::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$126, "Added Goat", References.ENTITY));
        Schema $$127 = dataFixerBuilder0.addSchema(2679, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new CauldronRenameFix($$127, false));
        Schema $$128 = dataFixerBuilder0.addSchema(2680, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$128, "Renamed grass path item to dirt path", createRenamer("minecraft:grass_path", "minecraft:dirt_path")));
        dataFixerBuilder0.addFixer(BlockRenameFixWithJigsaw.create($$128, "Renamed grass path block to dirt path", createRenamer("minecraft:grass_path", "minecraft:dirt_path")));
        Schema $$129 = dataFixerBuilder0.addSchema(2684, V2684::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$129, "Added Sculk Sensor", References.BLOCK_ENTITY));
        Schema $$130 = dataFixerBuilder0.addSchema(2686, V2686::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$130, "Added Axolotl", References.ENTITY));
        Schema $$131 = dataFixerBuilder0.addSchema(2688, V2688::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$131, "Added Glow Squid", References.ENTITY));
        dataFixerBuilder0.addFixer(new AddNewChoices($$131, "Added Glow Item Frame", References.ENTITY));
        Schema $$132 = dataFixerBuilder0.addSchema(2690, SAME_NAMESPACED);
        ImmutableMap<String, String> $$133 = ImmutableMap.builder().put("minecraft:weathered_copper_block", "minecraft:oxidized_copper_block").put("minecraft:semi_weathered_copper_block", "minecraft:weathered_copper_block").put("minecraft:lightly_weathered_copper_block", "minecraft:exposed_copper_block").put("minecraft:weathered_cut_copper", "minecraft:oxidized_cut_copper").put("minecraft:semi_weathered_cut_copper", "minecraft:weathered_cut_copper").put("minecraft:lightly_weathered_cut_copper", "minecraft:exposed_cut_copper").put("minecraft:weathered_cut_copper_stairs", "minecraft:oxidized_cut_copper_stairs").put("minecraft:semi_weathered_cut_copper_stairs", "minecraft:weathered_cut_copper_stairs").put("minecraft:lightly_weathered_cut_copper_stairs", "minecraft:exposed_cut_copper_stairs").put("minecraft:weathered_cut_copper_slab", "minecraft:oxidized_cut_copper_slab").put("minecraft:semi_weathered_cut_copper_slab", "minecraft:weathered_cut_copper_slab").put("minecraft:lightly_weathered_cut_copper_slab", "minecraft:exposed_cut_copper_slab").put("minecraft:waxed_semi_weathered_copper", "minecraft:waxed_weathered_copper").put("minecraft:waxed_lightly_weathered_copper", "minecraft:waxed_exposed_copper").put("minecraft:waxed_semi_weathered_cut_copper", "minecraft:waxed_weathered_cut_copper").put("minecraft:waxed_lightly_weathered_cut_copper", "minecraft:waxed_exposed_cut_copper").put("minecraft:waxed_semi_weathered_cut_copper_stairs", "minecraft:waxed_weathered_cut_copper_stairs").put("minecraft:waxed_lightly_weathered_cut_copper_stairs", "minecraft:waxed_exposed_cut_copper_stairs").put("minecraft:waxed_semi_weathered_cut_copper_slab", "minecraft:waxed_weathered_cut_copper_slab").put("minecraft:waxed_lightly_weathered_cut_copper_slab", "minecraft:waxed_exposed_cut_copper_slab").build();
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$132, "Renamed copper block items to new oxidized terms", createRenamer($$133)));
        dataFixerBuilder0.addFixer(BlockRenameFixWithJigsaw.create($$132, "Renamed copper blocks to new oxidized terms", createRenamer($$133)));
        Schema $$134 = dataFixerBuilder0.addSchema(2691, SAME_NAMESPACED);
        ImmutableMap<String, String> $$135 = ImmutableMap.builder().put("minecraft:waxed_copper", "minecraft:waxed_copper_block").put("minecraft:oxidized_copper_block", "minecraft:oxidized_copper").put("minecraft:weathered_copper_block", "minecraft:weathered_copper").put("minecraft:exposed_copper_block", "minecraft:exposed_copper").build();
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$134, "Rename copper item suffixes", createRenamer($$135)));
        dataFixerBuilder0.addFixer(BlockRenameFixWithJigsaw.create($$134, "Rename copper blocks suffixes", createRenamer($$135)));
        Schema $$136 = dataFixerBuilder0.addSchema(2693, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new AddFlagIfNotPresentFix($$136, References.WORLD_GEN_SETTINGS, "has_increased_height_already", false));
        Schema $$137 = dataFixerBuilder0.addSchema(2696, SAME_NAMESPACED);
        ImmutableMap<String, String> $$138 = ImmutableMap.builder().put("minecraft:grimstone", "minecraft:deepslate").put("minecraft:grimstone_slab", "minecraft:cobbled_deepslate_slab").put("minecraft:grimstone_stairs", "minecraft:cobbled_deepslate_stairs").put("minecraft:grimstone_wall", "minecraft:cobbled_deepslate_wall").put("minecraft:polished_grimstone", "minecraft:polished_deepslate").put("minecraft:polished_grimstone_slab", "minecraft:polished_deepslate_slab").put("minecraft:polished_grimstone_stairs", "minecraft:polished_deepslate_stairs").put("minecraft:polished_grimstone_wall", "minecraft:polished_deepslate_wall").put("minecraft:grimstone_tiles", "minecraft:deepslate_tiles").put("minecraft:grimstone_tile_slab", "minecraft:deepslate_tile_slab").put("minecraft:grimstone_tile_stairs", "minecraft:deepslate_tile_stairs").put("minecraft:grimstone_tile_wall", "minecraft:deepslate_tile_wall").put("minecraft:grimstone_bricks", "minecraft:deepslate_bricks").put("minecraft:grimstone_brick_slab", "minecraft:deepslate_brick_slab").put("minecraft:grimstone_brick_stairs", "minecraft:deepslate_brick_stairs").put("minecraft:grimstone_brick_wall", "minecraft:deepslate_brick_wall").put("minecraft:chiseled_grimstone", "minecraft:chiseled_deepslate").build();
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$137, "Renamed grimstone block items to deepslate", createRenamer($$138)));
        dataFixerBuilder0.addFixer(BlockRenameFixWithJigsaw.create($$137, "Renamed grimstone blocks to deepslate", createRenamer($$138)));
        Schema $$139 = dataFixerBuilder0.addSchema(2700, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(BlockRenameFixWithJigsaw.create($$139, "Renamed cave vines blocks", createRenamer(ImmutableMap.of("minecraft:cave_vines_head", "minecraft:cave_vines", "minecraft:cave_vines_body", "minecraft:cave_vines_plant"))));
        Schema $$140 = dataFixerBuilder0.addSchema(2701, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new SavedDataFeaturePoolElementFix($$140));
        Schema $$141 = dataFixerBuilder0.addSchema(2702, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new AbstractArrowPickupFix($$141));
        Schema $$142 = dataFixerBuilder0.addSchema(2704, V2704::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$142, "Added Goat", References.ENTITY));
        Schema $$143 = dataFixerBuilder0.addSchema(2707, V2707::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$143, "Added Marker", References.ENTITY));
        dataFixerBuilder0.addFixer(new AddFlagIfNotPresentFix($$143, References.WORLD_GEN_SETTINGS, "has_increased_height_already", true));
        Schema $$144 = dataFixerBuilder0.addSchema(2710, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new StatsRenameFix($$144, "Renamed play_one_minute stat to play_time", ImmutableMap.of("minecraft:play_one_minute", "minecraft:play_time")));
        Schema $$145 = dataFixerBuilder0.addSchema(2717, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$145, "Rename azalea_leaves_flowers", createRenamer(ImmutableMap.of("minecraft:azalea_leaves_flowers", "minecraft:flowering_azalea_leaves"))));
        dataFixerBuilder0.addFixer(BlockRenameFix.create($$145, "Rename azalea_leaves_flowers items", createRenamer(ImmutableMap.of("minecraft:azalea_leaves_flowers", "minecraft:flowering_azalea_leaves"))));
        Schema $$146 = dataFixerBuilder0.addSchema(2825, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new AddFlagIfNotPresentFix($$146, References.WORLD_GEN_SETTINGS, "has_increased_height_already", false));
        Schema $$147 = dataFixerBuilder0.addSchema(2831, V2831::new);
        dataFixerBuilder0.addFixer(new SpawnerDataFix($$147));
        Schema $$148 = dataFixerBuilder0.addSchema(2832, V2832::new);
        dataFixerBuilder0.addFixer(new WorldGenSettingsHeightAndBiomeFix($$148));
        dataFixerBuilder0.addFixer(new ChunkHeightAndBiomeFix($$148));
        Schema $$149 = dataFixerBuilder0.addSchema(2833, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new WorldGenSettingsDisallowOldCustomWorldsFix($$149));
        Schema $$150 = dataFixerBuilder0.addSchema(2838, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new NamespacedTypeRenameFix($$150, "Caves and Cliffs biome renames", References.BIOME, createRenamer(CavesAndCliffsRenames.RENAMES)));
        Schema $$151 = dataFixerBuilder0.addSchema(2841, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new ChunkProtoTickListFix($$151));
        Schema $$152 = dataFixerBuilder0.addSchema(2842, V2842::new);
        dataFixerBuilder0.addFixer(new ChunkRenamesFix($$152));
        Schema $$153 = dataFixerBuilder0.addSchema(2843, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new OverreachingTickFix($$153));
        dataFixerBuilder0.addFixer(new NamespacedTypeRenameFix($$153, "Remove Deep Warm Ocean", References.BIOME, createRenamer("minecraft:deep_warm_ocean", "minecraft:warm_ocean")));
        Schema $$154 = dataFixerBuilder0.addSchema(2846, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new AdvancementsRenameFix($$154, false, "Rename some C&C part 2 advancements", createRenamer(ImmutableMap.of("minecraft:husbandry/play_jukebox_in_meadows", "minecraft:adventure/play_jukebox_in_meadows", "minecraft:adventure/caves_and_cliff", "minecraft:adventure/fall_from_world_height", "minecraft:adventure/ride_strider_in_overworld_lava", "minecraft:nether/ride_strider_in_overworld_lava"))));
        Schema $$155 = dataFixerBuilder0.addSchema(2852, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new WorldGenSettingsDisallowOldCustomWorldsFix($$155));
        Schema $$156 = dataFixerBuilder0.addSchema(2967, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new StructureSettingsFlattenFix($$156));
        Schema $$157 = dataFixerBuilder0.addSchema(2970, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new StructuresBecomeConfiguredFix($$157));
        Schema $$158 = dataFixerBuilder0.addSchema(3076, V3076::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$158, "Added Sculk Catalyst", References.BLOCK_ENTITY));
        Schema $$159 = dataFixerBuilder0.addSchema(3077, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new ChunkDeleteIgnoredLightDataFix($$159));
        Schema $$160 = dataFixerBuilder0.addSchema(3078, V3078::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$160, "Added Frog", References.ENTITY));
        dataFixerBuilder0.addFixer(new AddNewChoices($$160, "Added Tadpole", References.ENTITY));
        dataFixerBuilder0.addFixer(new AddNewChoices($$160, "Added Sculk Shrieker", References.BLOCK_ENTITY));
        Schema $$161 = dataFixerBuilder0.addSchema(3081, V3081::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$161, "Added Warden", References.ENTITY));
        Schema $$162 = dataFixerBuilder0.addSchema(3082, V3082::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$162, "Added Chest Boat", References.ENTITY));
        Schema $$163 = dataFixerBuilder0.addSchema(3083, V3083::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$163, "Added Allay", References.ENTITY));
        Schema $$164 = dataFixerBuilder0.addSchema(3084, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new NamespacedTypeRenameFix($$164, "game_event_renames_3084", References.GAME_EVENT_NAME, createRenamer(ImmutableMap.builder().put("minecraft:block_press", "minecraft:block_activate").put("minecraft:block_switch", "minecraft:block_activate").put("minecraft:block_unpress", "minecraft:block_deactivate").put("minecraft:block_unswitch", "minecraft:block_deactivate").put("minecraft:drinking_finish", "minecraft:drink").put("minecraft:elytra_free_fall", "minecraft:elytra_glide").put("minecraft:entity_damaged", "minecraft:entity_damage").put("minecraft:entity_dying", "minecraft:entity_die").put("minecraft:entity_killed", "minecraft:entity_die").put("minecraft:mob_interact", "minecraft:entity_interact").put("minecraft:ravager_roar", "minecraft:entity_roar").put("minecraft:ring_bell", "minecraft:block_change").put("minecraft:shulker_close", "minecraft:container_close").put("minecraft:shulker_open", "minecraft:container_open").put("minecraft:wolf_shaking", "minecraft:entity_shake").build())));
        Schema $$165 = dataFixerBuilder0.addSchema(3086, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new EntityVariantFix($$165, "Change cat variant type", References.ENTITY, "minecraft:cat", "CatType", Util.make(new Int2ObjectOpenHashMap(), p_216528_ -> {
            p_216528_.defaultReturnValue("minecraft:tabby");
            p_216528_.put(0, "minecraft:tabby");
            p_216528_.put(1, "minecraft:black");
            p_216528_.put(2, "minecraft:red");
            p_216528_.put(3, "minecraft:siamese");
            p_216528_.put(4, "minecraft:british");
            p_216528_.put(5, "minecraft:calico");
            p_216528_.put(6, "minecraft:persian");
            p_216528_.put(7, "minecraft:ragdoll");
            p_216528_.put(8, "minecraft:white");
            p_216528_.put(9, "minecraft:jellie");
            p_216528_.put(10, "minecraft:all_black");
        })::get));
        ImmutableMap<String, String> $$166 = ImmutableMap.builder().put("textures/entity/cat/tabby.png", "minecraft:tabby").put("textures/entity/cat/black.png", "minecraft:black").put("textures/entity/cat/red.png", "minecraft:red").put("textures/entity/cat/siamese.png", "minecraft:siamese").put("textures/entity/cat/british_shorthair.png", "minecraft:british").put("textures/entity/cat/calico.png", "minecraft:calico").put("textures/entity/cat/persian.png", "minecraft:persian").put("textures/entity/cat/ragdoll.png", "minecraft:ragdoll").put("textures/entity/cat/white.png", "minecraft:white").put("textures/entity/cat/jellie.png", "minecraft:jellie").put("textures/entity/cat/all_black.png", "minecraft:all_black").build();
        dataFixerBuilder0.addFixer(new CriteriaRenameFix($$165, "Migrate cat variant advancement", "minecraft:husbandry/complete_catalogue", p_216517_ -> (String) $$166.getOrDefault(p_216517_, p_216517_)));
        Schema $$167 = dataFixerBuilder0.addSchema(3087, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new EntityVariantFix($$167, "Change frog variant type", References.ENTITY, "minecraft:frog", "Variant", Util.make(new Int2ObjectOpenHashMap(), p_216519_ -> {
            p_216519_.put(0, "minecraft:temperate");
            p_216519_.put(1, "minecraft:warm");
            p_216519_.put(2, "minecraft:cold");
        })::get));
        Schema $$168 = dataFixerBuilder0.addSchema(3090, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new EntityPaintingFieldsRenameFix($$168));
        Schema $$169 = dataFixerBuilder0.addSchema(3093, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new EntityGoatMissingStateFix($$169));
        Schema $$170 = dataFixerBuilder0.addSchema(3094, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new GoatHornIdFix($$170));
        Schema $$171 = dataFixerBuilder0.addSchema(3097, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new FilteredBooksFix($$171));
        dataFixerBuilder0.addFixer(new FilteredSignsFix($$171));
        Map<String, String> $$172 = Map.of("minecraft:british", "minecraft:british_shorthair");
        dataFixerBuilder0.addFixer(new VariantRenameFix($$171, "Rename british shorthair", References.ENTITY, "minecraft:cat", $$172));
        dataFixerBuilder0.addFixer(new CriteriaRenameFix($$171, "Migrate cat variant advancement for british shorthair", "minecraft:husbandry/complete_catalogue", p_216531_ -> (String) $$172.getOrDefault(p_216531_, p_216531_)));
        dataFixerBuilder0.addFixer(new PoiTypeRemoveFix($$171, "Remove unpopulated villager PoI types", Set.of("minecraft:unemployed", "minecraft:nitwit")::contains));
        Schema $$173 = dataFixerBuilder0.addSchema(3108, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new BlendingDataRemoveFromNetherEndFix($$173));
        Schema $$174 = dataFixerBuilder0.addSchema(3201, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new OptionsProgrammerArtFix($$174));
        Schema $$175 = dataFixerBuilder0.addSchema(3202, V3202::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$175, "Added Hanging Sign", References.BLOCK_ENTITY));
        Schema $$176 = dataFixerBuilder0.addSchema(3203, V3203::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$176, "Added Camel", References.ENTITY));
        Schema $$177 = dataFixerBuilder0.addSchema(3204, V3204::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$177, "Added Chiseled Bookshelf", References.BLOCK_ENTITY));
        Schema $$178 = dataFixerBuilder0.addSchema(3209, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new ItemStackSpawnEggFix($$178, false, "minecraft:pig_spawn_egg"));
        Schema $$179 = dataFixerBuilder0.addSchema(3214, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new OptionsAmbientOcclusionFix($$179));
        Schema $$180 = dataFixerBuilder0.addSchema(3319, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new OptionsAccessibilityOnboardFix($$180));
        Schema $$181 = dataFixerBuilder0.addSchema(3322, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new EffectDurationFix($$181));
        Schema $$182 = dataFixerBuilder0.addSchema(3325, V3325::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$182, "Added displays", References.ENTITY));
        Schema $$183 = dataFixerBuilder0.addSchema(3326, V3326::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$183, "Added Sniffer", References.ENTITY));
        Schema $$184 = dataFixerBuilder0.addSchema(3327, V3327::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$184, "Archaeology", References.BLOCK_ENTITY));
        Schema $$185 = dataFixerBuilder0.addSchema(3328, V3328::new);
        dataFixerBuilder0.addFixer(new AddNewChoices($$185, "Added interaction", References.ENTITY));
        Schema $$186 = dataFixerBuilder0.addSchema(3438, V3438::new);
        dataFixerBuilder0.addFixer(BlockEntityRenameFix.create($$186, "Rename Suspicious Sand to Brushable Block", createRenamer("minecraft:suspicious_sand", "minecraft:brushable_block")));
        dataFixerBuilder0.addFixer(new EntityBrushableBlockFieldsRenameFix($$186));
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$186, "Pottery shard renaming", createRenamer(ImmutableMap.of("minecraft:pottery_shard_archer", "minecraft:archer_pottery_shard", "minecraft:pottery_shard_prize", "minecraft:prize_pottery_shard", "minecraft:pottery_shard_arms_up", "minecraft:arms_up_pottery_shard", "minecraft:pottery_shard_skull", "minecraft:skull_pottery_shard"))));
        dataFixerBuilder0.addFixer(new AddNewChoices($$186, "Added calibrated sculk sensor", References.BLOCK_ENTITY));
        Schema $$187 = dataFixerBuilder0.addSchema(3439, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new BlockEntitySignDoubleSidedEditableTextFix($$187, "Updated sign text format for Signs", "minecraft:sign"));
        dataFixerBuilder0.addFixer(new BlockEntitySignDoubleSidedEditableTextFix($$187, "Updated sign text format for Hanging Signs", "minecraft:hanging_sign"));
        Schema $$188 = dataFixerBuilder0.addSchema(3440, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new NamespacedTypeRenameFix($$188, "Replace experimental 1.20 overworld", References.MULTI_NOISE_BIOME_SOURCE_PARAMETER_LIST, createRenamer("minecraft:overworld_update_1_20", "minecraft:overworld")));
        dataFixerBuilder0.addFixer(new FeatureFlagRemoveFix($$188, "Remove 1.20 feature toggle", Set.of("minecraft:update_1_20")));
        Schema $$189 = dataFixerBuilder0.addSchema(3441, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new BlendingDataFix($$189));
        Schema $$190 = dataFixerBuilder0.addSchema(3447, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(ItemRenameFix.create($$190, "Pottery shard item renaming to Pottery sherd", createRenamer((Map<String, String>) Stream.of("minecraft:angler_pottery_shard", "minecraft:archer_pottery_shard", "minecraft:arms_up_pottery_shard", "minecraft:blade_pottery_shard", "minecraft:brewer_pottery_shard", "minecraft:burn_pottery_shard", "minecraft:danger_pottery_shard", "minecraft:explorer_pottery_shard", "minecraft:friend_pottery_shard", "minecraft:heart_pottery_shard", "minecraft:heartbreak_pottery_shard", "minecraft:howl_pottery_shard", "minecraft:miner_pottery_shard", "minecraft:mourner_pottery_shard", "minecraft:plenty_pottery_shard", "minecraft:prize_pottery_shard", "minecraft:sheaf_pottery_shard", "minecraft:shelter_pottery_shard", "minecraft:skull_pottery_shard", "minecraft:snort_pottery_shard").collect(Collectors.toMap(Function.identity(), p_280993_ -> p_280993_.replace("_pottery_shard", "_pottery_sherd"))))));
        Schema $$191 = dataFixerBuilder0.addSchema(3448, V3448::new);
        dataFixerBuilder0.addFixer(new DecoratedPotFieldRenameFix($$191));
        Schema $$192 = dataFixerBuilder0.addSchema(3450, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new RemapChunkStatusFix($$192, "Remove liquid_carvers and heightmap chunk statuses", createRenamer(Map.of("minecraft:liquid_carvers", "minecraft:carvers", "minecraft:heightmaps", "minecraft:spawn"))));
        Schema $$193 = dataFixerBuilder0.addSchema(3451, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new ChunkDeleteLightFix($$193));
        Schema $$194 = dataFixerBuilder0.addSchema(3459, SAME_NAMESPACED);
        dataFixerBuilder0.addFixer(new LegacyDragonFightFix($$194));
    }

    private static UnaryOperator<String> createRenamer(Map<String, String> mapStringString0) {
        return p_216526_ -> (String) mapStringString0.getOrDefault(p_216526_, p_216526_);
    }

    private static UnaryOperator<String> createRenamer(String string0, String string1) {
        return p_216523_ -> Objects.equals(p_216523_, string0) ? string1 : p_216523_;
    }
}