@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.xkmc.modulargolems.compat.materials.l2complements;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;