@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.xkmc.modulargolems.content.menu.registry;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;