@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.apace100.origins.screen;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;