@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.almostreliable.summoningrituals.compat.jei.ingredient.mob;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;