@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.github.edwinmindcraft.origins.api.util;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;