@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package mezz.jei.common.transfer;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;