@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package extensions.net.minecraft.world.entity.item.ItemEntity;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;