@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.almostreliable.lootjs.predicate;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;