@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package mezz.jei.api.ingredients.subtypes;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;