@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.xkmc.l2artifacts.content.client.select;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;